"""Interactive Diagram Builder (Archify-inspired)

Turns any structured document (PRD, brief, feature list) into a standalone
interactive HTML diagram — the Archify pattern: "describe it to your agent,
get an explorable visual you can share."

Differences vs PulseRadar's static SVG DiagramAgent (PaperBanana pattern):
  * Nodes collapse/expand on click (progressive disclosure of detail)
  * Pan (drag) and zoom (wheel / + - buttons)
  * Hover highlighting of connected edges
  * Everything inline: single HTML file, no dependencies, works offline

Layout: left-to-right hierarchy — Root → ## sections → bullet items.
Deterministic (no LLM call), so it renders instantly and never hallucinates.
"""
import html
import re
from typing import Any, Dict, List, Optional


def _esc(v: str) -> str:
    return html.escape(v or "", quote=True)


def parse_document(markdown: str, title: str) -> Dict[str, Any]:
    """Extracts root → sections → items hierarchy from markdown."""
    sections: List[Dict[str, Any]] = []
    current: Optional[Dict[str, Any]] = None
    root_desc = ""

    for raw in markdown.splitlines():
        line = raw.rstrip()
        if re.match(r"^#{2,3}\s+\S", line):          # ## / ### section
            name = re.sub(r"^#{2,3}\s+", "", line).strip()
            if name.lower().startswith(("prd", "generated by", "table of contents")):
                continue
            current = {"name": name, "items": []}
            sections.append(current)
        elif line.startswith("# ") and not title:
            title = line[2:].strip()
        elif re.match(r"^[-*]\s+\S", line) and current is not None:
            item = re.sub(r"^[-*]\s+", "", line)
            item = re.sub(r"\*\*(.+?)\*\*", r"\1", item).strip()
            if 0 < len(item) <= 220:
                current["items"].append(item)
        elif line.strip() and not sections and not root_desc and not line.startswith(("#", "|", "```")):
            root_desc = line.strip()[:160]

    return {"title": title or "Interactive Diagram", "root_desc": root_desc,
            "sections": sections[:14], "max_items": 8}


NODE_W, NODE_H = 210, 64
SEC_W, SEC_H = 230, 58
ITEM_W, ITEM_H = 250, 44
V_GAP, SEC_V_GAP = 12, 34


def compute_layout(doc: Dict[str, Any]) -> Dict[str, Any]:
    """Positions nodes in a left→right tree with collision-free rows."""
    sections = []
    y = 80
    for sec in doc["sections"]:
        items = sec["items"][: doc["max_items"]]
        sec_y = y
        item_nodes = []
        iy = sec_y - (max(0, len(items) - 1) * (ITEM_H + V_GAP)) / 2 if items else sec_y
        for i, it in enumerate(items):
            item_nodes.append({
                "id": f"i{len(sections)}_{i}",
                "x": 600, "y": iy + i * (ITEM_H + V_GAP),
                "w": ITEM_W, "h": ITEM_H,
                "label": it,
                "parent": f"s{len(sections)}",
            })
        if items:
            ys = [n["y"] for n in item_nodes]
            sec_y = (min(ys) + max(ys) + ITEM_H) / 2 - SEC_H / 2
        sections.append({
            "id": f"s{len(sections)}",
            "x": 310, "y": sec_y, "w": SEC_W, "h": SEC_H,
            "label": sec["name"],
            "items": item_nodes,
        })
        y = max(sec_y + SEC_H, (item_nodes[-1]["y"] + ITEM_H if item_nodes else sec_y + SEC_H)) + SEC_V_GAP

    root_y = 80
    if sections:
        ys = [s["y"] for s in sections]
        root_y = (min(ys) + max(ys) + SEC_H) / 2 - NODE_H / 2
    root = {"id": "root", "x": 40, "y": root_y, "w": NODE_W, "h": NODE_H,
            "label": doc["title"], "desc": doc["root_desc"]}

    total_h = max(560, (max((s["y"] + SEC_H for s in sections), default=560)) + 80)
    total_w = 600 + ITEM_W + 60
    return {"root": root, "sections": sections, "width": total_w, "height": total_h}


def build_interactive_diagram_html(title: str, markdown: str) -> str:
    """Renders the full standalone interactive HTML."""
    doc = parse_document(markdown, title)
    layout = compute_layout(doc)
    t = _esc(doc["title"])

    def node_svg(n: Dict[str, Any], cls: str, truncate: int = 42) -> str:
        label = n["label"] if len(n["label"]) <= truncate else n["label"][:truncate - 1] + "…"
        extra = ""
        if n.get("desc"):
            extra = (f'<text x="{n["x"] + NODE_W / 2}" y="{n["y"] + NODE_H - 10}" '
                     f'text-anchor="middle" class="nd-desc">{_esc(n["desc"][:44])}</text>')
        return (
            f'<g class="node {cls}" data-id="{n["id"]}">'
            f'<rect x="{n["x"]}" y="{n["y"]}" width="{n["w"]}" height="{n["h"]}" rx="12"/>'
            f'<text x="{n["x"] + n["w"] / 2}" y="{n["y"] + (26 if n.get("desc") else n["h"] / 2 + 5)}" '
            f'text-anchor="middle" class="nd-label">{_esc(label)}</text>{extra}</g>'
        )

    parts: List[str] = []

    # Edges root → sections (with hover path classes)
    for s in layout["sections"]:
        x1 = layout["root"]["x"] + NODE_W
        y1 = layout["root"]["y"] + NODE_H / 2
        x2 = s["x"]
        y2 = s["y"] + SEC_H / 2
        mx = (x1 + x2) / 2
        parts.append(
            f'<path class="edge edge-root" data-sec="{s["id"]}" '
            f'd="M {x1} {y1} C {mx} {y1}, {mx} {y2}, {x2} {y2}"/>'
        )
    # Section → item edges
    for s in layout["sections"]:
        for it in s["items"]:
            x1 = s["x"] + SEC_W
            y1 = s["y"] + SEC_H / 2
            x2 = it["x"]
            y2 = it["y"] + ITEM_H / 2
            mx = (x1 + x2) / 2
            parts.append(
                f'<path class="edge edge-item" data-sec="{s["id"]}" '
                f'd="M {x1} {y1} C {mx} {y1}, {mx} {y2}, {x2} {y2}"/>'
            )

    # Nodes
    parts.append(node_svg(layout["root"], "node-root"))
    for s in layout["sections"]:
        parts.append(
            f'<g class="node node-sec" data-id="{s["id"]}">'
            f'<rect x="{s["x"]}" y="{s["y"]}" width="{s["w"]}" height="{s["h"]}" rx="10"/>'
            f'<circle cx="{s["x"] + 18}" cy="{s["y"] + SEC_H / 2}" r="4" class="sec-dot"/>'
            f'<text x="{s["x"] + 32}" y="{s["y"] + SEC_H / 2 + 5}" class="nd-label sec-label">{_esc(s["label"][:30])}</text>'
            f'<text x="{s["x"] + s["w"] - 12}" y="{s["y"] + SEC_H / 2 + 5}" text-anchor="end" class="collapse-icon" '
            f'data-sec="{s["id"]}">−</text></g>'
        )
        for it in s["items"]:
            label = it["label"] if len(it["label"]) <= 38 else it["label"][:37] + "…"
            parts.append(
                f'<g class="node node-item" data-sec="{s["id"]}">'
                f'<rect x="{it["x"]}" y="{it["y"]}" width="{it["w"]}" height="{it["h"]}" rx="8"/>'
                f'<text x="{it["x"] + 12}" y="{it["y"] + ITEM_H / 2 + 4}" class="nd-item">{_esc(label)}</text></g>'
            )

    body = "".join(parts)
    w, h = layout["width"], layout["height"]

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{t} — Interactive Diagram</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; margin: 0; }}
  body {{ background: #0c0d10; color: #e8eaed; font-family: 'Inter', -apple-system, 'Segoe UI', sans-serif;
         overflow: hidden; height: 100vh; display: flex; flex-direction: column; }}
  header {{ padding: 14px 20px; border-bottom: 1px solid #292d30; display: flex; align-items: center;
            justify-content: space-between; gap: 12px; flex-wrap: wrap; }}
  header h1 {{ font-size: 15px; font-weight: 600; letter-spacing: -0.01em; }}
  header .hint {{ font: 11px monospace; color: #6e727a; }}
  .btns {{ display: flex; gap: 6px; }}
  .btns button {{ background: #000; border: 1px solid #292d30; color: #a1a4a5; width: 30px; height: 30px;
                  border-radius: 8px; cursor: pointer; font-size: 15px; }}
  .btns button:hover {{ color: #fff; border-color: #9281f7; }}
  #stage {{ flex: 1; overflow: hidden; cursor: grab; }}
  #stage.dragging {{ cursor: grabbing; }}
  svg {{ width: 100%; height: 100%; display: block; }}
  .edge {{ fill: none; stroke: #292d30; stroke-width: 1.5; transition: stroke .15s, opacity .2s; }}
  .edge-item {{ stroke: #23262b; stroke-dasharray: none; }}
  .edge:hover, svg.hl .edge-root {{ stroke: #9281f7; }}
  svg.zoomed-out .node text {{ display: none; }}
  .node rect {{ fill: #14161a; stroke: #292d30; stroke-width: 1; transition: stroke .15s; }}
  .node:hover rect {{ stroke: #9281f7; }}
  .node-root rect {{ fill: rgba(146,129,247,0.12); stroke: #9281f7; }}
  .node-sec rect {{ fill: #171a20; }}
  .node-item rect {{ fill: #101216; }}
  .nd-label {{ fill: #f0f0f0; font-size: 13px; font-weight: 600; font-family: inherit; }}
  .nd-desc {{ fill: #9ba1a6; font-size: 10.5px; font-family: monospace; }}
  .nd-item {{ fill: #c9cdd1; font-size: 11.5px; font-family: monospace; }}
  .sec-dot {{ fill: #9281f7; }}
  .collapse-icon {{ fill: #6e727a; font-size: 16px; cursor: pointer; font-family: monospace; }}
  .node-sec.collapsed .collapse-icon {{ fill: #9281f7; }}
  .node-sec.collapsed ~ g.hidden, g.item-group.hidden {{ display: none; }}
  footer {{ padding: 8px 20px; border-top: 1px solid #292d30; font: 10px monospace; color: #5c6063; }}
</style>
</head>
<body>
<header>
  <h1>{t}</h1>
  <span class="hint">drag to pan · scroll to zoom · click − to collapse a branch</span>
  <div class="btns">
    <button id="zin" title="Zoom in">+</button>
    <button id="zout" title="Zoom out">−</button>
    <button id="zfit" title="Fit to view" style="width:auto;padding:0 10px;font-size:11px;">fit</button>
  </div>
</header>
<div id="stage">
<svg id="viz" viewBox="0 0 {w} {h}">
  <g id="world">
    {body}
  </g>
</svg>
</div>
<footer>Archify-style interactive diagram · PulseRadar Lab · deterministic layout, zero hallucination</footer>
<script>
(function () {{
  var svg = document.getElementById('viz');
  var world = document.getElementById('world');
  var stage = document.getElementById('stage');
  var vb = {{ x: 0, y: 0, w: {w}, h: {h} }};
  function apply() {{ svg.setAttribute('viewBox', vb.x + ' ' + vb.y + ' ' + vb.w + ' ' + vb.h); }}
  function zoom(factor, cx, cy) {{
    var nw = Math.min(Math.max(vb.w * factor, {w} / 6), {w} * 3);
    var k = nw / vb.w;
    cx = cx === undefined ? vb.x + vb.w / 2 : cx;
    cy = cy === undefined ? vb.y + vb.h / 2 : cy;
    vb.x = cx - (cx - vb.x) * k; vb.y = cy - (cy - vb.y) * k;
    vb.w = nw; vb.h = vb.h * k; apply();
    svg.classList.toggle('zoomed-out', vb.w > {w} * 1.4);
  }}
  stage.addEventListener('wheel', function (e) {{
    e.preventDefault();
    var r = svg.getBoundingClientRect();
    var cx = vb.x + (e.clientX - r.left) / r.width * vb.w;
    var cy = vb.y + (e.clientY - r.top) / r.height * vb.h;
    zoom(e.deltaY > 0 ? 1.12 : 0.89, cx, cy);
  }}, {{ passive: false }});
  var drag = null;
  stage.addEventListener('pointerdown', function (e) {{
    drag = {{ x: e.clientX, y: e.clientY, vx: vb.x, vy: vb.y }};
    stage.classList.add('dragging'); stage.setPointerCapture(e.pointerId);
  }});
  stage.addEventListener('pointermove', function (e) {{
    if (!drag) return;
    var r = svg.getBoundingClientRect();
    vb.x = drag.vx - (e.clientX - drag.x) * vb.w / r.width;
    vb.y = drag.vy - (e.clientY - drag.y) * vb.h / r.height;
    apply();
  }});
  stage.addEventListener('pointerup', function () {{ drag = null; stage.classList.remove('dragging'); }});
  document.getElementById('zin').onclick = function () {{ zoom(0.8); }};
  document.getElementById('zout').onclick = function () {{ zoom(1.25); }};
  document.getElementById('zfit').onclick = function () {{ vb = {{ x: 0, y: 0, w: {w}, h: {h} }}; apply(); svg.classList.remove('zoomed-out'); }};

  // Collapse / expand section branches
  document.querySelectorAll('.collapse-icon').forEach(function (ic) {{
    ic.addEventListener('click', function (e) {{
      e.stopPropagation();
      var id = ic.getAttribute('data-sec');
      var g = ic.closest('.node');
      var collapsed = g.classList.toggle('collapsed');
      ic.textContent = collapsed ? '+' : '−';
      document.querySelectorAll('[data-sec="' + id + '"]').forEach(function (el) {{
        if (el === g) return;
        el.style.display = collapsed ? 'none' : '';
      }});
    }});
  }});
  apply();
}})();
</script>
</body>
</html>"""
