"""Diagram Agent — Auto-Generated SVG Diagrams (PaperBanana pattern)

A lightweight, dependency-free adaptation of PaperBanana's multi-agent
illustration pipeline: Planner → Visualizer → Critic. Given a PRD (or any
structured doc), it plans a diagram layout from the document's sections,
renders deterministic inline SVG, then critiques geometry (overlaps,
out-of-bounds, spacing) and re-renders with fixes.

Output is a standalone <svg> string that embeds cleanly into HTML briefs
and markdown exports.
"""
import re
import logging
from typing import Dict, Any, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Layout constants
CANVAS_W, CANVAS_H = 960, 540
MARGIN = 48
NODE_W, NODE_H = 210, 86
H_GAP, V_GAP = 60, 64


class DiagramAgent:
    """Plans and renders flow/layer diagrams from document structure."""

    # ------------------------------------------------------------------
    # Planner: extract structure from markdown PRD
    # ------------------------------------------------------------------
    def plan(self, markdown: str) -> Dict[str, Any]:
        sections: List[Dict[str, Any]] = []
        for m in re.finditer(r"^#{2,3}\s+(.+)$", markdown, re.M):
            title = m.group(1).strip().rstrip(":")
            if title.lower().startswith(("prd", "generated by", "table of contents")):
                continue
            sections.append({"title": title})

        # FR items under Functional Requirements
        frs = re.findall(r"[-*]\s*\*?\*?(FR-\d+)", markdown)
        features: List[str] = []
        for m in re.finditer(r"[-*]\s+\*?\*?([^*\n]{8,90})\*?\*?", markdown):
            candidate = m.group(1).strip()
            if candidate and not candidate.startswith(("FR-", "Reduction", "Time to")) and len(features) < 6:
                if any(k in candidate.lower() for k in ("shall", "provide", "system", "seamless", "detect", "support", "real-time", "automatic")):
                    features.append(candidate[:80])

        diagram_type = "flow" if len(sections) <= 5 else "layers"
        return {
            "diagram_type": diagram_type,
            "nodes": sections[:6],
            "features": features[:4],
        }

    # ------------------------------------------------------------------
    # Visualizer: deterministic layout + SVG
    # ------------------------------------------------------------------
    def _wrap_text(self, text: str, max_chars: int = 26, max_lines: int = 3) -> List[str]:
        words = text.split()
        lines: List[str] = []
        current = ""
        for w in words:
            if len(current) + len(w) + 1 <= max_chars:
                current = f"{current} {w}".strip()
            else:
                if current:
                    lines.append(current)
                current = w
                if len(lines) == max_lines:
                    break
        if current and len(lines) < max_lines:
            lines.append(current)
        if len(lines) == max_lines and words and " ".join(lines) != " ".join(words):
            lines[-1] = lines[-1][: max_chars - 1] + "…"
        return lines or [""]

    def _layout_flow(self, nodes: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Horizontal flow: 3 columns × 2 rows max, left→right, wrap to row 2."""
        positioned = []
        per_row = 3
        for i, node in enumerate(nodes):
            col = i % per_row
            row = i // per_row
            x = MARGIN + col * (NODE_W + H_GAP)
            y = MARGIN + row * (NODE_H + V_GAP) + 24
            positioned.append({**node, "x": x, "y": y, "index": i})
        return positioned

    def _layout_layers(self, nodes: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Vertical layer stack (foundation → surface)."""
        positioned = []
        for i, node in enumerate(nodes):
            x = MARGIN + 40 + (i % 2) * (NODE_W + H_GAP) if len(nodes) > 3 else MARGIN + (CANVAS_W - NODE_W) / 2
            y = MARGIN + i * (NODE_H + V_GAP) + 24 if len(nodes) <= 3 else MARGIN + (i // 2) * (NODE_H + V_GAP) + 24
            positioned.append({**node, "x": x, "y": y, "index": i})
        return positioned

    def _render(self, layout: List[Dict[str, Any]], features: List[str], title: str) -> str:
        parts: List[str] = []
        parts.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS_W} {CANVAS_H}" '
            f'font-family="-apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif">'
        )
        # Background
        parts.append(f'<rect width="{CANVAS_W}" height="{CANVAS_H}" rx="14" fill="#0b0b0d"/>')

        # Title
        parts.append(
            f'<text x="{MARGIN}" y="34" fill="#f0f0f0" font-size="17" font-weight="600">{self._esc(title[:60])}</text>'
        )

        accent = "#9281f7"
        border = "#3b3f45"

        # Connectors (flow arrows between consecutive nodes)
        for i in range(len(layout) - 1):
            a, b = layout[i], layout[i + 1]
            same_row = abs(a["y"] - b["y"]) < 10
            if same_row and b["x"] > a["x"]:
                x1 = a["x"] + NODE_W
                y1 = a["y"] + NODE_H / 2
                x2 = b["x"] - 10
                parts.append(
                    f'<line x1="{x1}" y1="{y1:.0f}" x2="{x2}" y2="{y1:.0f}" stroke="{accent}" stroke-width="1.6" marker-end="url(#arrow)"/>'
                )
            elif b["y"] > a["y"]:
                # Wrap-down connector
                x1 = a["x"] + NODE_W / 2
                y1 = a["y"] + NODE_H
                x2 = b["x"] + NODE_W / 2
                y2 = b["y"] - 10
                midy = (y1 + y2) / 2
                parts.append(
                    f'<path d="M {x1:.0f} {y1:.0f} L {x1:.0f} {midy:.0f} L {x2:.0f} {midy:.0f} L {x2:.0f} {y2:.0f}" '
                    f'fill="none" stroke="{accent}" stroke-width="1.6" marker-end="url(#arrow)" opacity="0.8"/>'
                )

        # Nodes
        for node in layout:
            lines = self._wrap_text(node["title"])
            x, y = node["x"], node["y"]
            parts.append(f'<rect x="{x}" y="{y}" width="{NODE_W}" height="{NODE_H}" rx="10" fill="#141417" stroke="{border}" stroke-width="1.2"/>')
            parts.append(f'<rect x="{x}" y="{y}" width="4" height="{NODE_H}" rx="2" fill="{accent}"/>')
            for li, line in enumerate(lines):
                ty = y + 34 + li * 17
                parts.append(
                    f'<text x="{x + 16}" y="{ty}" fill="#f0f0f0" font-size="12.5">{self._esc(line)}</text>'
                )
            parts.append(
                f'<text x="{x + NODE_W - 12}" y="{y + NODE_H - 10}" fill="#6e727a" font-size="9.5" text-anchor="end">{node["index"] + 1:02d}</text>'
            )

        # Feature strip at the bottom
        if features:
            strip_y = CANVAS_H - 64
            parts.append(f'<line x1="{MARGIN}" y1="{strip_y - 14}" x2="{CANVAS_W - MARGIN}" y2="{strip_y - 14}" stroke="{border}" stroke-width="1"/>')
            fx = MARGIN
            for feat in features[:4]:
                label = (feat[:34] + "…") if len(feat) > 34 else feat
                width = 9 * len(label) + 24
                if fx + width > CANVAS_W - MARGIN:
                    break
                parts.append(f'<rect x="{fx}" y="{strip_y}" width="{width}" height="30" rx="15" fill="#1a1425" stroke="rgba(146,129,247,0.45)" stroke-width="1"/>')
                parts.append(f'<text x="{fx + 12}" y="{strip_y + 19}" fill="#c9bffa" font-size="10.5">{self._esc(label)}</text>')
                fx += width + 12

        parts.append('<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#9281f7"/></marker></defs>')
        parts.append("</svg>")
        return "".join(parts)

    @staticmethod
    def _esc(text: str) -> str:
        return (
            str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
        )

    # ------------------------------------------------------------------
    # Critic: geometry validation + auto-fix pass
    # ------------------------------------------------------------------
    def critique(self, layout: List[Dict[str, Any]]) -> Dict[str, Any]:
        problems: List[str] = []
        fixes: List[str] = []

        for i, node in enumerate(layout):
            if node["x"] + NODE_W > CANVAS_W - MARGIN + 20:
                problems.append(f"Node {i} overflows right edge")
            if node["y"] + NODE_H > CANVAS_H - 70:
                problems.append(f"Node {i} collides with feature strip")
        # Overlap check
        for i in range(len(layout)):
            for j in range(i + 1, len(layout)):
                a, b = layout[i], layout[j]
                if (
                    a["x"] < b["x"] + NODE_W + 8
                    and b["x"] < a["x"] + NODE_W + 8
                    and a["y"] < b["y"] + NODE_H + 8
                    and b["y"] < a["y"] + NODE_H + 8
                ):
                    problems.append(f"Nodes {i} and {j} overlap")

        if problems:
            fixes.append("apply tighter per-row packing")
        return {"problems": problems, "fixes": fixes}

    def _relayout_tight(self, layout: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Critic-driven fallback: vertical stack packing that cannot collide."""
        relaid = []
        for i, node in enumerate(layout):
            relaid.append({**node, "x": MARGIN + 40, "y": MARGIN + i * (NODE_H + 24) + 24})
        return relaid

    # ------------------------------------------------------------------
    def generate(self, markdown: str, title: str = "System Architecture") -> Dict[str, Any]:
        """Full pipeline: plan → layout → render → critique → fix → re-render."""
        plan = self.plan(markdown)
        nodes = plan["nodes"]
        if not nodes:
            nodes = [{"title": "Problem", "index": 0}, {"title": "Solution", "index": 1}]

        if plan["diagram_type"] == "flow":
            layout = self._layout_flow(nodes)
        else:
            layout = self._layout_layers(nodes)

        svg = self._render(layout, plan["features"], title)

        critique = self.critique(layout)
        revision = 1
        if critique["problems"]:
            layout = self._relayout_tight(layout)
            svg = self._render(layout, plan["features"], title)
            critique2 = self.critique(layout)
            revision = 2
            critique = {
                "problems": critique["problems"],
                "fixed": not critique2["problems"],
                "remaining": critique2["problems"],
                "fixes_applied": ["vertical stack re-pack"],
            }

        return {
            "success": True,
            "diagram_type": plan["diagram_type"],
            "node_count": len(layout),
            "svg": svg,
            "revisions": revision,
            "critique": critique,
        }
