"""PulseRadar AI Model Catalog & Free Tier Knowledge Engine

Brings the full scope of FreeLLMAPI into PulseRadar:
- 7.4 Billion tokens per month aggregate free tier capacity
- 34 Free LLM Providers with quotas, rate limits, and setup guides
- 635+ Free and Open Model Endpoints with context windows, speed ranks, intelligence ranks
- Multi-dimensional filtering (context window, capabilities, free tier, provider, speed)
- OpenAI-compatible routing and dynamic provider selection
"""
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, asdict, field

@dataclass
class ModelEndpoint:
    id: str  # qualified id: platform/model_id
    platform: str
    provider_name: str
    model_id: str
    display_name: str
    family: str
    intelligence_rank: int  # 1 = Frontier, 15 = Small
    speed_rank: int  # 1 = Fastest (>800 tps), 10 = Standard
    size_label: str  # 'Frontier', 'Large', 'Medium', 'Small'
    context_window: int  # tokens
    rpm_limit: Optional[int] = None
    rpd_limit: Optional[int] = None
    tpm_limit: Optional[int] = None
    tpd_limit: Optional[int] = None
    monthly_token_budget: str = "~6M"
    monthly_token_budget_tokens: int = 6_000_000
    supports_vision: bool = False
    supports_tools: bool = True
    is_reasoning: bool = False
    is_coding: bool = False
    requires_card: bool = False
    base_url: str = ""
    key_format_hint: str = "Bearer token"
    recommended_use: str = "General reasoning and product analysis"
    modality: str = "chat"  # chat, embedding, image, video, audio, fusion

@dataclass
class ProviderInfo:
    platform: str
    name: str
    description: str
    monthly_free_tokens: str
    free_tier_models_count: int
    requires_credit_card: bool
    is_keyless_supported: bool
    signup_url: str
    key_url: str
    rate_limit_summary: str
    key_setup_guide: str
    gotchas_and_tips: str
    default_base_url: str

# ---------------------------------------------------------------------------
# 34 Free LLM Providers Directory with Free Tier Knowledge Base
# ---------------------------------------------------------------------------
PROVIDERS_DIRECTORY: Dict[str, ProviderInfo] = {
    "google": ProviderInfo(
        platform="google",
        name="Google AI Studio",
        description="Google Gemini 2.5 Flash, Pro, and Flash-Lite models with up to 1M token context windows.",
        monthly_free_tokens="~120M tokens/month (Flash-Lite) / ~25M (Flash)",
        free_tier_models_count=5,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://aistudio.google.com/",
        key_url="https://aistudio.google.com/app/apikey",
        rate_limit_summary="15 RPM, 20-1000 RPD, 250K TPM per model per project.",
        key_setup_guide="Sign in with any standard Google account at aistudio.google.com, click 'Get API key' -> 'Create API key in new project'. No credit card required.",
        gotchas_and_tips="Gemini 2.5 Flash-Lite grants the highest free volume (~1000 RPD). Flash has a tighter 20 RPD cap. Pro variants have limited free calls.",
        default_base_url="https://generativelanguage.googleapis.com/v1beta/openai"
    ),
    "groq": ProviderInfo(
        platform="groq",
        name="Groq Cloud",
        description="Ultra-fast LPU inference (500-1,000 tok/sec) for Llama 3.3 70B, Qwen, and GPT-OSS models.",
        monthly_free_tokens="~15M tokens/month per model",
        free_tier_models_count=8,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://console.groq.com/",
        key_url="https://console.groq.com/keys",
        rate_limit_summary="30 RPM, 1,000 RPD, 6K-12K TPM (up to 14,400 RPD on 8B instant).",
        key_setup_guide="Create a free account at console.groq.com (GitHub/Google login), navigate to API Keys -> Create Key. Instant activation with zero card required.",
        gotchas_and_tips="Scout and Llama 4 models require the 'meta-llama/' publisher prefix. The 8B instant model has a massive 14,400 daily request allowance.",
        default_base_url="https://api.groq.com/openai/v1"
    ),
    "cerebras": ProviderInfo(
        platform="cerebras",
        name="Cerebras Cloud",
        description="World's fastest inference engine powered by the CS-3 Wafer-Scale Engine (>2,000 tok/sec).",
        monthly_free_tokens="~30M tokens/month (1M tokens/day)",
        free_tier_models_count=5,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://cloud.cerebras.ai/",
        key_url="https://cloud.cerebras.ai/",
        rate_limit_summary="30 RPM, 60K TPM, 1,000,000 tokens per day free pool.",
        key_setup_guide="Sign up at cloud.cerebras.ai with GitHub or email. Generate API key from the developer console. 100% free with no card required.",
        gotchas_and_tips="Fastest TTFB in the world (~150ms). Excellent for high-speed clustering and signal distillation.",
        default_base_url="https://api.cerebras.ai/v1"
    ),
    "openrouter": ProviderInfo(
        platform="openrouter",
        name="OpenRouter (Free Pool)",
        description="Multi-model gateway aggregating free tiers of DeepSeek, Qwen Coder, MiniMax, and Nemotron.",
        monthly_free_tokens="~6M tokens/month across ':free' models",
        free_tier_models_count=18,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://openrouter.ai/",
        key_url="https://openrouter.ai/keys",
        rate_limit_summary="20 RPM, 200 RPD across all ':free' routes.",
        key_setup_guide="Create an account at openrouter.ai, generate a free API key. All models with the ':free' suffix cost $0 and draw from the free pool.",
        gotchas_and_tips="Always append ':free' to the model ID (e.g. 'deepseek/deepseek-v3.1:free'). Requires HTTP-Referer header.",
        default_base_url="https://openrouter.ai/api/v1"
    ),
    "github": ProviderInfo(
        platform="github",
        name="GitHub Models",
        description="Free developer inference for OpenAI GPT-4o, GPT-4.1, and Azure models directly using your GitHub PAT.",
        monthly_free_tokens="~18M tokens/month (GPT-4o) / ~9M (GPT-4.1)",
        free_tier_models_count=6,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://github.com/marketplace/models",
        key_url="https://github.com/settings/tokens",
        rate_limit_summary="15 RPM, 50-150 RPD, 8K in / 4K out per call.",
        key_setup_guide="Generate a classic or fine-grained Personal Access Token (PAT) with 'read:user' scope at github.com/settings/tokens. Use models.github.ai/inference.",
        gotchas_and_tips="Model IDs use 'openai/gpt-4o' or 'openai/gpt-4.1'. Uses standard GitHub PAT as the Bearer token.",
        default_base_url="https://models.github.ai/inference"
    ),
    "mistral": ProviderInfo(
        platform="mistral",
        name="Mistral AI (La Plateforme)",
        description="High-tier European models: Codestral, Devstral, Mistral Large, and Magistral Medium.",
        monthly_free_tokens="~50-100M tokens/month (shared 1B tokens/mo Experiment tier)",
        free_tier_models_count=6,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://console.mistral.ai/",
        key_url="https://console.mistral.ai/api-keys",
        rate_limit_summary="2 RPM, 500K TPM, shared 1B token/mo experiment pool.",
        key_setup_guide="Register at console.mistral.ai. Verify phone number for free experiment tier access. No payment card needed.",
        gotchas_and_tips="Codestral is top-ranked for code and structured PRDs. RPM is strictly capped at 2 requests/min on free tier.",
        default_base_url="https://api.mistral.ai/v1"
    ),
    "cohere": ProviderInfo(
        platform="cohere",
        name="Cohere",
        description="Enterprise RAG and reasoning models: Command R+, Command-A, and multilingual Embed.",
        monthly_free_tokens="~1-2M tokens/month (1,000 free calls/month)",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://cohere.com/",
        key_url="https://dashboard.cohere.com/api-keys",
        rate_limit_summary="20 RPM, 33 RPD, 1,000 requests/month trial pool.",
        key_setup_guide="Sign up at dashboard.cohere.com, create a trial key. Trial keys never expire and work on all standard endpoints.",
        gotchas_and_tips="High quality on tool use and enterprise citations. Monthly request limit is 1,000 calls total.",
        default_base_url="https://api.cohere.com/v1"
    ),
    "cloudflare": ProviderInfo(
        platform="cloudflare",
        name="Cloudflare Workers AI",
        description="Edge AI serving Llama 3.3 70B fp8-fast, GLM-4.7, and DeepSeek across 300+ data centers.",
        monthly_free_tokens="~18-45M tokens/month (10,000 Neurons/day free)",
        free_tier_models_count=10,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://dash.cloudflare.com/",
        key_url="https://dash.cloudflare.com/profile/api-tokens",
        rate_limit_summary="10,000 Neurons per day (~1M-1.5M tokens/day equivalent).",
        key_setup_guide="Sign up for Cloudflare free account. Create API token with 'Workers AI: Read' permissions. Endpoint uses Account ID.",
        gotchas_and_tips="Model IDs are prefixed with '@cf/' (e.g. '@cf/meta/llama-3.3-70b-instruct-fp8-fast').",
        default_base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1"
    ),
    "zhipu": ProviderInfo(
        platform="zhipu",
        name="Zhipu AI (Z.ai / BigModel)",
        description="GLM-4.5 Flash and GLM-4.7 frontier reasoning models with long-context support.",
        monthly_free_tokens="~30M tokens/month (1M tokens/day)",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://bigmodel.cn/",
        key_url="https://bigmodel.cn/usercenter/apikeys",
        rate_limit_summary="1,000,000 tokens per day free quota on Flash models.",
        key_setup_guide="Register at bigmodel.cn or z.ai with phone/email. Free key is generated instantly in the user center.",
        gotchas_and_tips="Reasoning models (GLM-4.7) output reasoning_content tokens first. Set timeout to >= 60s for cold starts.",
        default_base_url="https://open.bigmodel.cn/api/paas/v4"
    ),
    "huggingface": ProviderInfo(
        platform="huggingface",
        name="Hugging Face Router",
        description="Inference Providers router proxying dozens of open-source models with $0.10/mo recurring credit.",
        monthly_free_tokens="~1-3M tokens/month free credits",
        free_tier_models_count=12,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://huggingface.co/",
        key_url="https://huggingface.co/settings/tokens",
        rate_limit_summary="Dynamic based on provider backend; monthly router credit.",
        key_setup_guide="Sign up at huggingface.co, create a User Access Token with inference permissions.",
        gotchas_and_tips="Uses router.huggingface.co/v1 with standard OpenAI completions format.",
        default_base_url="https://router.huggingface.co/v1"
    ),
    "ollama": ProviderInfo(
        platform="ollama",
        name="Ollama Cloud",
        description="Hosted cloud version of Ollama offering verified free community models.",
        monthly_free_tokens="~15M tokens/month (GPU session hours)",
        free_tier_models_count=6,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://ollama.com/",
        key_url="https://ollama.com/settings/keys",
        rate_limit_summary="1 concurrent model, 5h session caps on free plan.",
        key_setup_guide="Sign up at ollama.com, generate an API key from user settings.",
        gotchas_and_tips="Provides OpenAI-compatible endpoints on /v1.",
        default_base_url="https://ollama.com/v1"
    ),
    "kilo": ProviderInfo(
        platform="kilo",
        name="Kilo Gateway",
        description="Anonymous keyless aggregator providing free access to open-source models.",
        monthly_free_tokens="~10M tokens/month",
        free_tier_models_count=5,
        requires_credit_card=False,
        is_keyless_supported=True,
        signup_url="https://kilo.ai/",
        key_url="https://kilo.ai/",
        rate_limit_summary="200 requests/hour per IP anonymous tier.",
        key_setup_guide="No key needed! Kilo allows keyless requests to free models with rate limits per IP.",
        gotchas_and_tips="Keyless access is available for all models ending in ':free'.",
        default_base_url="https://api.kilo.ai/api/gateway/v1"
    ),
    "pollinations": ProviderInfo(
        platform="pollinations",
        name="Pollinations AI",
        description="Free, community-powered open inference for text and image models.",
        monthly_free_tokens="~15M tokens/month (fair use)",
        free_tier_models_count=7,
        requires_credit_card=False,
        is_keyless_supported=True,
        signup_url="https://pollinations.ai/",
        key_url="https://pollinations.ai/",
        rate_limit_summary="Fair use community capacity, ~10-20 RPM.",
        key_setup_guide="Zero setup required: supports anonymous access or free community tokens.",
        gotchas_and_tips="Ideal as a zero-auth fallback provider for quick tests and embeddings.",
        default_base_url="https://text.pollinations.ai/openai"
    ),
    "opencode": ProviderInfo(
        platform="opencode",
        name="OpenCode Zen",
        description="Developer-focused AI gateway with free promotional coding models.",
        monthly_free_tokens="~10M tokens/month",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://opencode.ai/auth",
        key_url="https://opencode.ai/keys",
        rate_limit_summary="20 RPM on free developer accounts.",
        key_setup_guide="Register at opencode.ai with GitHub or email for an instant free API key.",
        gotchas_and_tips="Tuned for SWE-bench and coding tasks.",
        default_base_url="https://api.opencode.ai/v1"
    ),
    "ovh": ProviderInfo(
        platform="ovh",
        name="OVHcloud AI Endpoints",
        description="European cloud provider offering keyless anonymous inference on open models.",
        monthly_free_tokens="~5M tokens/month",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=True,
        signup_url="https://endpoints.ai.cloud.ovh.net/",
        key_url="https://endpoints.ai.cloud.ovh.net/",
        rate_limit_summary="2 requests/min per IP per model anonymous tier.",
        key_setup_guide="Anonymous calls permitted directly via European endpoints.",
        gotchas_and_tips="100% GDPR compliant European hosting.",
        default_base_url="https://endpoints.ai.cloud.ovh.net/v1"
    ),
    "siliconflow": ProviderInfo(
        platform="siliconflow",
        name="SiliconFlow",
        description="High-speed model inference serving free DeepSeek, Qwen, and FLUX models.",
        monthly_free_tokens="~20M tokens/month (recurring free tier)",
        free_tier_models_count=8,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://siliconflow.com/",
        key_url="https://cloud.siliconflow.cn/account/ak",
        rate_limit_summary="Up to 1000 requests/day on verified free tiers.",
        key_setup_guide="Sign up at siliconflow.com with email. Generate free key from account dashboard.",
        gotchas_and_tips="Excellent performance on DeepSeek V3 and Qwen 2.5 Coder.",
        default_base_url="https://api.siliconflow.cn/v1"
    ),
    "aihorde": ProviderInfo(
        platform="aihorde",
        name="AI Horde",
        description="Decentralized volunteer compute grid serving open source LLMs and generative art.",
        monthly_free_tokens="Unlimited (queue-based volunteer computing)",
        free_tier_models_count=15,
        requires_credit_card=False,
        is_keyless_supported=True,
        signup_url="https://aihorde.net/",
        key_url="https://aihorde.net/register",
        rate_limit_summary="Queue based; anonymous key '0000000000' works with lower queue priority.",
        key_setup_guide="Use anonymous key '0000000000' or register for a free account to earn kudos.",
        gotchas_and_tips="Requests may take 10-30s depending on volunteer queue depth.",
        default_base_url="https://oai.aihorde.net/v1"
    ),
    "nvidia": ProviderInfo(
        platform="nvidia",
        name="NVIDIA NIM",
        description="Enterprise NVIDIA-hosted NIM microservices (Llama 3.3, Nemotron 70B, DeepSeek).",
        monthly_free_tokens="Credits-based free trial allowance",
        free_tier_models_count=6,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://build.nvidia.com/",
        key_url="https://build.nvidia.com/",
        rate_limit_summary="40 RPM per model on free developer credits.",
        key_setup_guide="Sign in with NVIDIA developer account at build.nvidia.com, click 'Get API Key'.",
        gotchas_and_tips="Reasoning models may take 30-60s on cold start. Force single tool call.",
        default_base_url="https://integrate.api.nvidia.com/v1"
    ),
    "sambanova": ProviderInfo(
        platform="sambanova",
        name="SambaNova Cloud",
        description="Reconfigurable Dataflow Unit (RDU) inference for DeepSeek V3 and Llama 3.3 70B.",
        monthly_free_tokens="~3M tokens/month (200K TPD developer tier)",
        free_tier_models_count=5,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://cloud.sambanova.ai/",
        key_url="https://cloud.sambanova.ai/apis",
        rate_limit_summary="20 RPM, 20 RPD, 200,000 tokens/day free Developer pool.",
        key_setup_guide="Create a free developer account at cloud.sambanova.ai to access RDU inference.",
        gotchas_and_tips="Strict 20 RPD limit on free tier. DeepSeek V3.2 is high-intelligence.",
        default_base_url="https://api.sambanova.ai/v1"
    ),
    "modelscope": ProviderInfo(
        platform="modelscope",
        name="ModelScope (Alibaba)",
        description="Alibaba Cloud community hub offering Qwen 2.5/3, DeepSeek, and GLM models.",
        monthly_free_tokens="~2,000 requests/day account-wide",
        free_tier_models_count=8,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://modelscope.cn/",
        key_url="https://modelscope.cn/my/myaccesstoken",
        rate_limit_summary="2,000 requests per day account-wide.",
        key_setup_guide="Sign up at modelscope.cn. Generate AccessToken in account settings.",
        gotchas_and_tips="Best source for experimental Qwen releases.",
        default_base_url="https://api-inference.modelscope.cn/v1"
    ),
    "reka": ProviderInfo(
        platform="reka",
        name="Reka AI",
        description="Native multimodal frontier models (text, images, audio, video) with Flash-Edge tiers.",
        monthly_free_tokens="~5M tokens/month free developer grant",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://platform.reka.ai/",
        key_url="https://platform.reka.ai/",
        rate_limit_summary="20 RPM on standard free developer tier.",
        key_setup_guide="Register at platform.reka.ai for developer API key.",
        gotchas_and_tips="Exceptional multimodal ingestion for video research analysis.",
        default_base_url="https://api.reka.ai/v1"
    ),
    "agnes": ProviderInfo(
        platform="agnes",
        name="Agnes AI (Sapiens)",
        description="Proprietary fast inference engine built on LiteLLM and optimized vLLM clusters.",
        monthly_free_tokens="~8M tokens/month",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://platform.agnes-ai.com/",
        key_url="https://platform.agnes-ai.com/",
        rate_limit_summary="15 RPM on verified no-card developer tier.",
        key_setup_guide="Create a free key at platform.agnes-ai.com without entering payment details.",
        gotchas_and_tips="High consistency on structured JSON outputs.",
        default_base_url="https://api.agnes-ai.com/v1"
    ),
    "routeway": ProviderInfo(
        platform="routeway",
        name="Routeway AI",
        description="Smart aggregator routing requests across available zero-cost free models.",
        monthly_free_tokens="~5M tokens/month",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://routeway.ai/",
        key_url="https://routeway.ai/",
        rate_limit_summary="5 RPM on free tier routes.",
        key_setup_guide="Sign up at routeway.ai for a free API key.",
        gotchas_and_tips="Free routes use the ':free' model alias.",
        default_base_url="https://api.routeway.ai/v1"
    ),
    "bazaarlink": ProviderInfo(
        platform="bazaarlink",
        name="BazaarLink",
        description="Community inference marketplace offering the zero-cost 'auto:free' smart route.",
        monthly_free_tokens="~6M tokens/month",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://bazaarlink.ai/",
        key_url="https://bazaarlink.ai/",
        rate_limit_summary="10 RPM on free aliases.",
        key_setup_guide="Register at bazaarlink.ai without credit card.",
        gotchas_and_tips="Use 'auto:free' model to automatically pick currently un-congested node.",
        default_base_url="https://api.bazaarlink.ai/v1"
    ),
    "ainative": ProviderInfo(
        platform="ainative",
        name="AINative Studio",
        description="Developer studio with recurring 10M tokens/month free allocation.",
        monthly_free_tokens="~10M tokens/month recurring free tier",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://ainative.studio/",
        key_url="https://ainative.studio/",
        rate_limit_summary="20 RPM, 10,000,000 tokens per month free.",
        key_setup_guide="Sign up with email at ainative.studio and claim your free developer tier.",
        gotchas_and_tips="High monthly token allowance.",
        default_base_url="https://api.ainative.studio/v1"
    ),
    "aion": ProviderInfo(
        platform="aion",
        name="Aion Labs",
        description="Unified inference gateway offering no-card free developer access.",
        monthly_free_tokens="~5M tokens/month",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://aionlabs.ai/",
        key_url="https://aionlabs.ai/",
        rate_limit_summary="15 RPM free tier allowance.",
        key_setup_guide="Sign up for free developer key at aionlabs.ai.",
        gotchas_and_tips="Reliable fallback for general text summarization.",
        default_base_url="https://api.aionlabs.ai/v1"
    ),
    "requesty": ProviderInfo(
        platform="requesty",
        name="Requesty Router",
        description="Multi-provider AI router with dedicated zero-cost model pool.",
        monthly_free_tokens="~6M tokens/month",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://requesty.ai/",
        key_url="https://requesty.ai/",
        rate_limit_summary="10 RPM on free tier.",
        key_setup_guide="Create an account at requesty.ai to get free routing token.",
        gotchas_and_tips="Built-in automatic retry logic.",
        default_base_url="https://api.requesty.ai/v1"
    ),
    "navy": ProviderInfo(
        platform="navy",
        name="NavyAI",
        description="Unified API with 150K tokens/day free plan and 20 RPM rate limit.",
        monthly_free_tokens="~4.5M tokens/month (150K tokens/day)",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://navyai.com/",
        key_url="https://navyai.com/",
        rate_limit_summary="20 RPM, 150,000 tokens/day free plan.",
        key_setup_guide="Register at navyai.com without entering credit card.",
        gotchas_and_tips="Resets daily at 00:00 UTC.",
        default_base_url="https://api.navyai.com/v1"
    ),
    "nara": ProviderInfo(
        platform="nara",
        name="NaraRouter",
        description="Fast regional inference gateway with daily-resetting free plan routes.",
        monthly_free_tokens="~5M tokens/month",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://router.bynara.id/",
        key_url="https://router.bynara.id/",
        rate_limit_summary="10 RPM, daily free quota.",
        key_setup_guide="Get account key from router.bynara.id after channel verification.",
        gotchas_and_tips="Great latency in South East Asia region.",
        default_base_url="https://router.bynara.id/v1"
    ),
    "sealion": ProviderInfo(
        platform="sealion",
        name="SEA-LION (AI Singapore)",
        description="Southeast Asian Language in One Network (SEA-LION) frontier models.",
        monthly_free_tokens="~3M tokens/month (10 RPM free)",
        free_tier_models_count=3,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://aisingapore.org/",
        key_url="https://aisingapore.org/",
        rate_limit_summary="10 RPM free tier, Google sign-in.",
        key_setup_guide="Sign in with Google at AI Singapore portal. No region wall or card needed.",
        gotchas_and_tips="Excels at regional ASEAN languages and localization nuances.",
        default_base_url="https://api.sea-lion.ai/v1"
    ),
    "orcarouter": ProviderInfo(
        platform="orcarouter",
        name="OrcaRouter",
        description="OpenAI-compatible aggregator with rate-limited free aliases that never bill.",
        monthly_free_tokens="~5M tokens/month",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://orcarouter.ai/",
        key_url="https://orcarouter.ai/",
        rate_limit_summary="10 RPM, 100% free aliases at $0 cost.",
        key_setup_guide="Register at orcarouter.ai with email.",
        gotchas_and_tips="Guaranteed never to fall back to paid routes.",
        default_base_url="https://api.orcarouter.ai/v1"
    ),
    "unorouter": ProviderInfo(
        platform="unorouter",
        name="UnoRouter",
        description="Aggregator with free models carrying ':free' suffix and per-minute limits.",
        monthly_free_tokens="~4M tokens/month",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://unorouter.com/",
        key_url="https://unorouter.com/",
        rate_limit_summary="5 RPM on free models, 429 backoff.",
        key_setup_guide="Sign up at unorouter.com for a free API token.",
        gotchas_and_tips="Model IDs carry ':free' suffix.",
        default_base_url="https://api.unorouter.com/v1"
    ),
    "xkiro": ProviderInfo(
        platform="xkiro",
        name="xKiro",
        description="High-capacity gateway with 5M tokens/day free plan on open models.",
        monthly_free_tokens="~150M tokens/month (5M tokens/day)",
        free_tier_models_count=4,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://xkiro.com/",
        key_url="https://xkiro.com/",
        rate_limit_summary="20 RPM, 5,000,000 tokens/day free tier.",
        key_setup_guide="Sign up at xkiro.com for free developer key.",
        gotchas_and_tips="Huge daily token ceiling (5M/day).",
        default_base_url="https://api.xkiro.com/v1"
    ),
    "volcengine": ProviderInfo(
        platform="volcengine",
        name="Volcengine Ark (ByteDance)",
        description="ByteDance cloud serving Doubao, DeepSeek, and Llama with 2M tokens/day per model.",
        monthly_free_tokens="~60M tokens/month (2M tokens/day/model)",
        free_tier_models_count=6,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://ark.cn-beijing.volces.com/",
        key_url="https://console.volcengine.com/ark",
        rate_limit_summary="2,000,000 tokens per day per model recurring reward.",
        key_setup_guide="Sign up at volcengine.com. Requires developer account registration.",
        gotchas_and_tips="Strongest recurring daily allowance in mainland cloud providers.",
        default_base_url="https://ark.cn-beijing.volces.com/api/v3"
    ),
    "freellmapi_local": ProviderInfo(
        platform="freellmapi_local",
        name="FreeLLMAPI Unified Gateway",
        description="Local FreeLLMAPI instance aggregating all 34 free providers and 635 endpoints behind one port.",
        monthly_free_tokens="7.4+ Billion tokens/month (across all enabled keys)",
        free_tier_models_count=635,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="http://localhost:3001",
        key_url="http://localhost:3001/keys",
        rate_limit_summary="Aggregates and load-balances across all configured provider keys.",
        key_setup_guide="Run FreeLLMAPI locally via Docker or Node, configure your provider keys, and grab the unified Bearer token from the dashboard.",
        gotchas_and_tips="Automatic fallover on 429/5xx errors, smart bandit routing, and zero token waste.",
        default_base_url="http://localhost:3001/v1"
    ),
        "moondream": ProviderInfo(
        platform="moondream",
        name="Moondream Vision",
        description="Tiny, fast vision-language model for image captioning, visual QA, and object detection.",
        monthly_free_tokens="~5M tokens/month (recurring free tier)",
        free_tier_models_count=1,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://moondream.ai/",
        key_url="https://console.moondream.ai/",
        rate_limit_summary="60 RPM, $5/mo free recurring credit.",
        key_setup_guide="Create a free account at console.moondream.ai. Generate API key from dashboard. Zero credit card needed.",
        gotchas_and_tips="Optimized for visual question answering and extracting UI wireframe information.",
        default_base_url="https://api.moondream.ai/v1"
    ),
    "speechify": ProviderInfo(
        platform="speechify",
        name="Speechify Neural TTS",
        description="High-fidelity neural text-to-speech engine with ultra-low latency audio synthesis.",
        monthly_free_tokens="~1M characters/month free",
        free_tier_models_count=1,
        requires_credit_card=False,
        is_keyless_supported=False,
        signup_url="https://speechify.com/",
        key_url="https://speechify.com/api",
        rate_limit_summary="30 RPM free rate limit.",
        key_setup_guide="Sign up for free developer access at speechify.com/api. Zero card required for free tier.",
        gotchas_and_tips="Produces broadcast-grade voice synthesis from text PRD summaries.",
        default_base_url="https://api.sws.speechify.com/v1"
    ),
    "fusion": ProviderInfo(
        platform="fusion",
        name="PulseRadar Multi-Model Consensus",
        description="Parallel ensemble fusion combining Groq, Cerebras, and Google responses with automated arbitration.",
        monthly_free_tokens="Unlimited (draws from underlying free providers)",
        free_tier_models_count=1,
        requires_credit_card=False,
        is_keyless_supported=True,
        signup_url="https://pulseradar.local",
        key_url="",
        rate_limit_summary="Governed by underlying provider rate limits.",
        key_setup_guide="Zero setup required. Routes consensus queries across configured healthy free provider keys.",
        gotchas_and_tips="Maximizes reasoning correctness by synthesizing answers across 3 distinct model architectures.",
        default_base_url="https://pulseradar.local/fusion"
    ),
    "custom": ProviderInfo(
        platform="custom",
        name="Custom OpenAI-Compatible",
        description="Any self-hosted or private model server (Ollama, vLLM, LM Studio, llama.cpp, LocalAI).",
        monthly_free_tokens="Unlimited (Self-Hosted)",
        free_tier_models_count=1,
        requires_credit_card=False,
        is_keyless_supported=True,
        signup_url="",
        key_url="",
        rate_limit_summary="Hardware-bound concurrency and throughput.",
        key_setup_guide="Point base URL to your local Ollama (http://localhost:11434/v1), vLLM (http://localhost:8000/v1), or LM Studio (http://localhost:1234/v1).",
        gotchas_and_tips="Ensure CORS is enabled if accessing directly from browser environments.",
        default_base_url="http://localhost:11434/v1"
    )
}


# ---------------------------------------------------------------------------
# Comprehensive Model Registry (Seed Catalog)
# ---------------------------------------------------------------------------
CATALOG_MODELS: List[ModelEndpoint] = [
    # =========================================================================
    # 1. CHAT & REASONING MODELS (All 36 Providers Represented)
    # =========================================================================
    # --- Google AI Studio ---
    ModelEndpoint(
        id="google/gemini-flash-latest",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemini-flash-latest",
        display_name="Gemini Flash (Latest)",
        family="Gemini",
        intelligence_rank=4,
        speed_rank=2,
        size_label="Large",
        context_window=1_048_576,
        rpm_limit=15,
        rpd_limit=1500,
        tpm_limit=250_000,
        monthly_token_budget="~120M",
        monthly_token_budget_tokens=120_000_000,
        supports_vision=True,
        supports_tools=True,
        is_reasoning=False,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Live verified primary Google Gemini Flash with 1M token context and 1,500 RPD",
        modality="chat"
    ),
    ModelEndpoint(
        id="google/gemini-flash-lite-latest",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemini-flash-lite-latest",
        display_name="Gemini Flash-Lite (Latest)",
        family="Gemini",
        intelligence_rank=6,
        speed_rank=1,
        size_label="Medium",
        context_window=1_048_576,
        rpm_limit=15,
        rpd_limit=1500,
        tpm_limit=250_000,
        monthly_token_budget="~150M",
        monthly_token_budget_tokens=150_000_000,
        supports_vision=True,
        supports_tools=True,
        is_reasoning=False,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Massive throughput signal processing with 1M context (~150M free tokens/mo)",
        modality="chat"
    ),
    ModelEndpoint(
        id="google/gemini-3.1-flash-lite",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemini-3.1-flash-lite",
        display_name="Gemini 3.1 Flash-Lite",
        family="Gemini",
        intelligence_rank=5,
        speed_rank=1,
        size_label="Medium",
        context_window=1_048_576,
        rpm_limit=15,
        rpd_limit=1000,
        tpm_limit=250_000,
        monthly_token_budget="~120M",
        monthly_token_budget_tokens=120_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Next-gen ultra-fast multimodal model with 1M token window",
        modality="chat"
    ),
    ModelEndpoint(
        id="google/gemini-3-flash-preview",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemini-3-flash-preview",
        display_name="Gemini 3 Flash Preview",
        family="Gemini",
        intelligence_rank=3,
        speed_rank=2,
        size_label="Frontier",
        context_window=1_048_576,
        rpm_limit=10,
        rpd_limit=500,
        tpm_limit=250_000,
        monthly_token_budget="~50M",
        monthly_token_budget_tokens=50_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Frontier Gemini 3 preview for complex technical requirements and strategy",
        modality="chat"
    ),
    ModelEndpoint(
        id="google/gemini-3.1-pro-preview",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemini-3.1-pro-preview",
        display_name="Gemini 3.1 Pro Preview",
        family="Gemini",
        intelligence_rank=1,
        speed_rank=6,
        size_label="Frontier",
        context_window=1_048_576,
        rpm_limit=5,
        rpd_limit=50,
        tpm_limit=250_000,
        monthly_token_budget="~10M",
        monthly_token_budget_tokens=10_000_000,
        supports_vision=True,
        supports_tools=True,
        is_reasoning=True,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Deep chain-of-thought frontier reasoning recommended by Google for advanced PRD synthesis",
        modality="chat"
    ),
    ModelEndpoint(
        id="google/gemma-4-26b-a4b-it",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemma-4-26b-a4b-it",
        display_name="Gemma 4 26B (Google)",
        family="Gemma",
        intelligence_rank=5,
        speed_rank=3,
        size_label="Large",
        context_window=262_144,
        rpm_limit=15,
        rpd_limit=1000,
        monthly_token_budget="~50M",
        monthly_token_budget_tokens=50_000_000,
        supports_tools=True,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Open weights dense architecture hosted on Google AI Studio infrastructure",
        modality="chat"
    ),

    # --- Groq Cloud ---
    ModelEndpoint(
        id="groq/llama-3.3-70b-versatile",
        platform="groq",
        provider_name="Groq Cloud",
        model_id="llama-3.3-70b-versatile",
        display_name="Llama 3.3 70B Versatile",
        family="Llama",
        intelligence_rank=6,
        speed_rank=1,
        size_label="Large",
        context_window=131_072,
        rpm_limit=30,
        rpd_limit=1000,
        tpm_limit=6000,
        tpd_limit=500_000,
        monthly_token_budget="~15M",
        monthly_token_budget_tokens=15_000_000,
        supports_vision=False,
        supports_tools=True,
        base_url="https://api.groq.com/openai/v1",
        recommended_use="Instant low-latency hypothesis generation and user interview structuring (500 tok/sec)",
        modality="chat"
    ),
    ModelEndpoint(
        id="groq/meta-llama/llama-4-scout-17b-16e-instruct",
        platform="groq",
        provider_name="Groq Cloud",
        model_id="meta-llama/llama-4-scout-17b-16e-instruct",
        display_name="Llama 4 Scout",
        family="Llama",
        intelligence_rank=8,
        speed_rank=1,
        size_label="Medium",
        context_window=131_072,
        rpm_limit=30,
        rpd_limit=1000,
        tpm_limit=6000,
        tpd_limit=1_000_000,
        monthly_token_budget="~30M",
        monthly_token_budget_tokens=30_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://api.groq.com/openai/v1",
        recommended_use="Blazing-fast multimodal synthesis, diagram analysis, fast roadmapping",
        modality="chat"
    ),
    ModelEndpoint(
        id="groq/llama-3.1-8b-instant",
        platform="groq",
        provider_name="Groq Cloud",
        model_id="llama-3.1-8b-instant",
        display_name="Llama 3.1 8B Instant",
        family="Llama",
        intelligence_rank=12,
        speed_rank=1,
        size_label="Small",
        context_window=131_072,
        rpm_limit=30,
        rpd_limit=14400,
        tpm_limit=20_000,
        monthly_token_budget="~60M",
        monthly_token_budget_tokens=60_000_000,
        supports_vision=False,
        supports_tools=True,
        base_url="https://api.groq.com/openai/v1",
        recommended_use="High-volume real-time token streaming and automated tagging (14,400 RPD allowance)",
        modality="chat"
    ),
    ModelEndpoint(
        id="groq/qwen-2.5-32b",
        platform="groq",
        provider_name="Groq Cloud",
        model_id="qwen-2.5-32b",
        display_name="Qwen 2.5 32B (Groq)",
        family="Qwen",
        intelligence_rank=7,
        speed_rank=1,
        size_label="Medium",
        context_window=131_072,
        rpm_limit=30,
        rpd_limit=1000,
        tpm_limit=6000,
        monthly_token_budget="~15M",
        monthly_token_budget_tokens=15_000_000,
        supports_tools=True,
        is_coding=True,
        base_url="https://api.groq.com/openai/v1",
        recommended_use="Ultra-fast code snippet analysis and structured user stories",
        modality="chat"
    ),

    # --- Cerebras Cloud ---
    ModelEndpoint(
        id="cerebras/qwen-3-235b-a22b-instruct-2507",
        platform="cerebras",
        provider_name="Cerebras Cloud",
        model_id="qwen-3-235b-a22b-instruct-2507",
        display_name="Qwen3 235B (Cerebras)",
        family="Qwen",
        intelligence_rank=3,
        speed_rank=1,
        size_label="Large",
        context_window=8192,
        rpm_limit=30,
        tpm_limit=60_000,
        tpd_limit=1_000_000,
        monthly_token_budget="~30M",
        monthly_token_budget_tokens=30_000_000,
        supports_tools=True,
        base_url="https://api.cerebras.ai/v1",
        recommended_use="World's fastest token generation (>2,000 tok/sec) on Cerebras CS-3 Wafer-Scale Engine",
        modality="chat"
    ),
    ModelEndpoint(
        id="cerebras/llama-3.3-70b",
        platform="cerebras",
        provider_name="Cerebras Cloud",
        model_id="llama-3.3-70b",
        display_name="Llama 3.3 70B (Cerebras)",
        family="Llama",
        intelligence_rank=6,
        speed_rank=1,
        size_label="Large",
        context_window=8192,
        rpm_limit=30,
        tpm_limit=60_000,
        tpd_limit=1_000_000,
        monthly_token_budget="~30M",
        monthly_token_budget_tokens=30_000_000,
        supports_tools=True,
        base_url="https://api.cerebras.ai/v1",
        recommended_use="Instantaneous real-time PRD draft generator with 150ms TTFB",
        modality="chat"
    ),

    # --- OpenRouter Free Pool ---
    ModelEndpoint(
        id="openrouter/nvidia/nemotron-3-super-120b-a12b:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="nvidia/nemotron-3-super-120b-a12b:free",
        display_name="Nemotron 3 Super 120B (free)",
        family="Nemotron",
        intelligence_rank=2,
        speed_rank=4,
        size_label="Frontier",
        context_window=262_144,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~10M",
        monthly_token_budget_tokens=10_000_000,
        supports_tools=True,
        is_reasoning=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Live verified primary OpenRouter free model with 262K context and frontier reasoning",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/qwen/qwen3.8-27b:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="qwen/qwen3.8-27b:free",
        display_name="Qwen 3.8 27B (free)",
        family="Qwen",
        intelligence_rank=3,
        speed_rank=3,
        size_label="Large",
        context_window=262_144,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        is_coding=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="High-capability coding and structured JSON generation on OpenRouter free pool",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/google/gemma-4-31b-it:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="google/gemma-4-31b-it:free",
        display_name="Gemma 4 31B (free OR)",
        family="Gemma",
        intelligence_rank=4,
        speed_rank=4,
        size_label="Large",
        context_window=262_144,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Google's open weights instruction model routed via OpenRouter free tier",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/google/gemma-4-26b-a4b-it:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="google/gemma-4-26b-a4b-it:free",
        display_name="Gemma 4 26B (free OR)",
        family="Gemma",
        intelligence_rank=5,
        speed_rank=3,
        size_label="Medium",
        context_window=262_144,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Fast instruction-tuned model for quick market research tasks",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/cohere/north-mini-code:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="cohere/north-mini-code:free",
        display_name="North Mini Code (free)",
        family="Command",
        intelligence_rank=5,
        speed_rank=3,
        size_label="Medium",
        context_window=256_000,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        is_coding=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Specialized code and architecture model with 256K token context",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/nvidia/nemotron-3.5-lightning:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="nvidia/nemotron-3.5-lightning:free",
        display_name="Nemotron 3.5 Lightning (free)",
        family="Nemotron",
        intelligence_rank=4,
        speed_rank=2,
        size_label="Large",
        context_window=1_000_000,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~8M",
        monthly_token_budget_tokens=8_000_000,
        supports_tools=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Massive 1M token context window model on OpenRouter free pool",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/thinkingmachines/inkling:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="thinkingmachines/inkling:free",
        display_name="Inkling 1M (free)",
        family="Universal",
        intelligence_rank=5,
        speed_rank=3,
        size_label="Large",
        context_window=1_048_576,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Whole-repository and long document research with 1M context",
        modality="chat"
    ),
    ModelEndpoint(
        id="openrouter/inclusionai/ling-3.0-flash-sante:free",
        platform="openrouter",
        provider_name="OpenRouter (Free Pool)",
        model_id="inclusionai/ling-3.0-flash-sante:free",
        display_name="Ling 3.0 Flash (free)",
        family="Universal",
        intelligence_rank=6,
        speed_rank=2,
        size_label="Medium",
        context_window=262_144,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        base_url="https://openrouter.ai/api/v1",
        recommended_use="Rapid text extraction and categorization with 262K context",
        modality="chat"
    ),

    # --- GitHub Models ---
    ModelEndpoint(
        id="github/openai/gpt-4o",
        platform="github",
        provider_name="GitHub Models",
        model_id="openai/gpt-4o",
        display_name="GPT-4o (GitHub)",
        family="OpenAI",
        intelligence_rank=5,
        speed_rank=3,
        size_label="Large",
        context_window=128_000,
        rpm_limit=15,
        rpd_limit=150,
        monthly_token_budget="~18M",
        monthly_token_budget_tokens=18_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://models.github.ai/inference",
        recommended_use="Free developer tier access to OpenAI flagship model using standard GitHub PAT",
        modality="chat"
    ),
    ModelEndpoint(
        id="github/openai/gpt-4.1",
        platform="github",
        provider_name="GitHub Models",
        model_id="openai/gpt-4.1",
        display_name="GPT-4.1 (GitHub)",
        family="OpenAI",
        intelligence_rank=4,
        speed_rank=3,
        size_label="Frontier",
        context_window=128_000,
        rpm_limit=10,
        rpd_limit=50,
        monthly_token_budget="~9M",
        monthly_token_budget_tokens=9_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://models.github.ai/inference",
        recommended_use="Latest generation GPT-4.1 with enhanced precision for product specifications",
        modality="chat"
    ),
    ModelEndpoint(
        id="github/openai/gpt-4o-mini",
        platform="github",
        provider_name="GitHub Models",
        model_id="openai/gpt-4o-mini",
        display_name="GPT-4o Mini (GitHub)",
        family="OpenAI",
        intelligence_rank=8,
        speed_rank=2,
        size_label="Small",
        context_window=128_000,
        rpm_limit=15,
        rpd_limit=150,
        monthly_token_budget="~20M",
        monthly_token_budget_tokens=20_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://models.github.ai/inference",
        recommended_use="Fast, high-fidelity lightweight analysis with zero credit card required",
        modality="chat"
    ),

    # --- Mistral AI ---
    ModelEndpoint(
        id="mistral/mistral-large-latest",
        platform="mistral",
        provider_name="Mistral AI",
        model_id="mistral-large-latest",
        display_name="Mistral Large 3",
        family="Mistral",
        intelligence_rank=5,
        speed_rank=4,
        size_label="Large",
        context_window=131_072,
        rpm_limit=2,
        tpm_limit=500_000,
        monthly_token_budget="~50-100M",
        monthly_token_budget_tokens=50_000_000,
        supports_tools=True,
        base_url="https://api.mistral.ai/v1",
        recommended_use="Sophisticated European frontier model with 1B token/mo shared experiment pool",
        modality="chat"
    ),
    ModelEndpoint(
        id="mistral/codestral-latest",
        platform="mistral",
        provider_name="Mistral AI",
        model_id="codestral-latest",
        display_name="Codestral",
        family="Mistral",
        intelligence_rank=6,
        speed_rank=3,
        size_label="Medium",
        context_window=32_000,
        rpm_limit=2,
        tpm_limit=500_000,
        monthly_token_budget="~50-100M",
        monthly_token_budget_tokens=50_000_000,
        supports_tools=True,
        is_coding=True,
        base_url="https://api.mistral.ai/v1",
        recommended_use="Benchmark-leading code understanding and structured technical documentation",
        modality="chat"
    ),
    ModelEndpoint(
        id="mistral/magistral-medium-latest",
        platform="mistral",
        provider_name="Mistral AI",
        model_id="magistral-medium-latest",
        display_name="Magistral Medium",
        family="Mistral",
        intelligence_rank=7,
        speed_rank=3,
        size_label="Medium",
        context_window=40_000,
        rpm_limit=2,
        tpm_limit=500_000,
        monthly_token_budget="~50-100M",
        monthly_token_budget_tokens=50_000_000,
        supports_tools=True,
        base_url="https://api.mistral.ai/v1",
        recommended_use="Reasoning and step-by-step logic distillation",
        modality="chat"
    ),

    # --- Cohere ---
    ModelEndpoint(
        id="cohere/command-r-plus-08-2024",
        platform="cohere",
        provider_name="Cohere",
        model_id="command-r-plus-08-2024",
        display_name="Command R+ (08-2024)",
        family="Command",
        intelligence_rank=8,
        speed_rank=5,
        size_label="Large",
        context_window=131_072,
        rpm_limit=20,
        rpd_limit=33,
        monthly_token_budget="~1-2M",
        monthly_token_budget_tokens=1_500_000,
        supports_tools=True,
        base_url="https://api.cohere.com/v2",
        recommended_use="World-class Retrieval Augmented Generation (RAG) and citation grounding",
        modality="chat"
    ),

    # --- Cloudflare Workers AI ---
    ModelEndpoint(
        id="cloudflare/@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        platform="cloudflare",
        provider_name="Cloudflare Workers AI",
        model_id="@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        display_name="Llama 3.3 70B fp8-fast (CF)",
        family="Llama",
        intelligence_rank=6,
        speed_rank=2,
        size_label="Large",
        context_window=131_072,
        monthly_token_budget="~18-45M",
        monthly_token_budget_tokens=25_000_000,
        supports_tools=True,
        base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        key_format_hint="account_id:token",
        recommended_use="Edge inference deployed globally across 300+ Cloudflare datacenter locations",
        modality="chat"
    ),
    ModelEndpoint(
        id="cloudflare/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
        platform="cloudflare",
        provider_name="Cloudflare Workers AI",
        model_id="@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
        display_name="DeepSeek R1 Distill Qwen 32B (CF)",
        family="DeepSeek",
        intelligence_rank=4,
        speed_rank=3,
        size_label="Medium",
        context_window=65_536,
        monthly_token_budget="~15M",
        monthly_token_budget_tokens=15_000_000,
        supports_tools=True,
        is_reasoning=True,
        base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        key_format_hint="account_id:token",
        recommended_use="Edge-hosted DeepSeek R1 reasoning on Cloudflare free tier",
        modality="chat"
    ),

    # --- Zhipu AI ---
    ModelEndpoint(
        id="zhipu/glm-4.5-flash",
        platform="zhipu",
        provider_name="Zhipu AI (BigModel)",
        model_id="glm-4.5-flash",
        display_name="GLM-4.5 Flash",
        family="GLM",
        intelligence_rank=7,
        speed_rank=2,
        size_label="Large",
        context_window=131_072,
        tpd_limit=1_000_000,
        monthly_token_budget="~30M",
        monthly_token_budget_tokens=30_000_000,
        supports_tools=True,
        base_url="https://open.bigmodel.cn/api/paas/v4",
        recommended_use="High-volume 1M tokens/day free allocation with strong bilingual support",
        modality="chat"
    ),
    ModelEndpoint(
        id="zhipu/glm-4.6v-flash",
        platform="zhipu",
        provider_name="Zhipu AI (BigModel)",
        model_id="glm-4.6v-flash",
        display_name="GLM-4.6V Flash Vision",
        family="GLM",
        intelligence_rank=7,
        speed_rank=3,
        size_label="Medium",
        context_window=131_072,
        monthly_token_budget="~20M",
        monthly_token_budget_tokens=20_000_000,
        supports_vision=True,
        supports_tools=True,
        base_url="https://open.bigmodel.cn/api/paas/v4",
        recommended_use="Free vision-language understanding for UI wireframes and competitive screenshots",
        modality="chat"
    ),

    # --- Hugging Face ---
    ModelEndpoint(
        id="huggingface/meta-llama/Llama-3.3-70B-Instruct",
        platform="huggingface",
        provider_name="Hugging Face (Inference Router)",
        model_id="meta-llama/Llama-3.3-70B-Instruct",
        display_name="Llama 3.3 70B (HF Router)",
        family="Llama",
        intelligence_rank=6,
        speed_rank=4,
        size_label="Large",
        context_window=131_072,
        monthly_token_budget="~3M",
        monthly_token_budget_tokens=3_000_000,
        supports_tools=True,
        base_url="https://router.huggingface.co/hf-inference/v1",
        recommended_use="Direct access via standard HuggingFace User Access Token (read scope)",
        modality="chat"
    ),

    # --- Ollama / Local ---
    ModelEndpoint(
        id="ollama/llama3.3:latest",
        platform="ollama",
        provider_name="Ollama Local Engine",
        model_id="llama3.3:latest",
        display_name="Llama 3.3 (Local Ollama)",
        family="Llama",
        intelligence_rank=6,
        speed_rank=5,
        size_label="Large",
        context_window=131_072,
        monthly_token_budget="Unlimited (Local GPU)",
        monthly_token_budget_tokens=100_000_000,
        supports_tools=True,
        base_url="http://localhost:11434/v1",
        key_format_hint="Keyless (localhost)",
        recommended_use="Private, offline, hardware-accelerated local inference with 0 API cost",
        modality="chat"
    ),
    ModelEndpoint(
        id="ollama/deepseek-r1:14b",
        platform="ollama",
        provider_name="Ollama Local Engine",
        model_id="deepseek-r1:14b",
        display_name="DeepSeek R1 14B (Local)",
        family="DeepSeek",
        intelligence_rank=5,
        speed_rank=4,
        size_label="Medium",
        context_window=65_536,
        monthly_token_budget="Unlimited (Local GPU)",
        monthly_token_budget_tokens=100_000_000,
        supports_tools=True,
        is_reasoning=True,
        base_url="http://localhost:11434/v1",
        key_format_hint="Keyless (localhost)",
        recommended_use="100% private local chain-of-thought reasoning without data leaving machine",
        modality="chat"
    ),

    # --- Keyless Providers (Zero Key Required) ---
    ModelEndpoint(
        id="kilo/free-chat-v1",
        platform="kilo",
        provider_name="Kilo Gateway (Keyless)",
        model_id="free-chat-v1",
        display_name="Kilo Free Chat (Zero Key)",
        family="Universal",
        intelligence_rank=8,
        speed_rank=3,
        size_label="Medium",
        context_window=65_536,
        rpm_limit=10,
        monthly_token_budget="Free Community Pool",
        monthly_token_budget_tokens=10_000_000,
        supports_tools=True,
        base_url="https://api.kilo.ai/v1",
        key_format_hint="No key required",
        recommended_use="Keyless community gateway for instant zero-configuration testing",
        modality="chat"
    ),
    ModelEndpoint(
        id="pollinations/openai-fast",
        platform="pollinations",
        provider_name="Pollinations.ai (Keyless)",
        model_id="openai-fast",
        display_name="Pollinations OpenAI Fast (Keyless)",
        family="Universal",
        intelligence_rank=9,
        speed_rank=2,
        size_label="Medium",
        context_window=32_768,
        monthly_token_budget="Community Fair-Use",
        monthly_token_budget_tokens=8_000_000,
        supports_tools=False,
        base_url="https://gen.pollinations.ai/v1",
        key_format_hint="No key required",
        recommended_use="Publishable community tier with zero authentication or signup needed",
        modality="chat"
    ),
    ModelEndpoint(
        id="ovh/mistral-7b-instruct",
        platform="ovh",
        provider_name="OVHcloud AI Endpoints (Keyless)",
        model_id="mistral-7b-instruct",
        display_name="Mistral 7B (OVH Keyless)",
        family="Mistral",
        intelligence_rank=11,
        speed_rank=4,
        size_label="Small",
        context_window=32_768,
        rpm_limit=2,
        monthly_token_budget="Free Fair-Use",
        monthly_token_budget_tokens=2_000_000,
        base_url="https://endpoints.ai.cloud.ovh.net/v1",
        key_format_hint="No key required (2 req/min)",
        recommended_use="Keyless anonymous European inference tier (2 req/min IP cap)",
        modality="chat"
    ),
    ModelEndpoint(
        id="aihorde/llama-3-70b-instruct",
        platform="aihorde",
        provider_name="AI Horde (Volunteer GPU)",
        model_id="llama-3-70b-instruct",
        display_name="Llama 3 70B (AI Horde)",
        family="Llama",
        intelligence_rank=8,
        speed_rank=9,
        size_label="Large",
        context_window=8192,
        monthly_token_budget="Community Kudos",
        monthly_token_budget_tokens=5_000_000,
        base_url="https://oai.aihorde.net/v1",
        key_format_hint="Keyless (anon: 0000000000)",
        recommended_use="Decentralized volunteer worker network (no rate caps, queue based)",
        modality="chat"
    ),

    # --- Additional Global & Specialized Free Providers ---
    ModelEndpoint(
        id="opencode/nemotron-3-ultra-free",
        platform="opencode",
        provider_name="OpenCode Zen",
        model_id="nemotron-3-ultra-free",
        display_name="Nemotron 3 Ultra Free",
        family="Nemotron",
        intelligence_rank=4,
        speed_rank=3,
        size_label="Frontier",
        context_window=131_072,
        rpm_limit=20,
        rpd_limit=200,
        monthly_token_budget="Free Promotional Tier",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        base_url="https://opencode.ai/api/v1",
        recommended_use="OpenCode Zen free promotion serving 550B Nemotron with fast tool calling",
        modality="chat"
    ),
    ModelEndpoint(
        id="siliconflow/deepseek-ai/DeepSeek-V3",
        platform="siliconflow",
        provider_name="SiliconFlow",
        model_id="deepseek-ai/DeepSeek-V3",
        display_name="DeepSeek V3 (SiliconFlow)",
        family="DeepSeek",
        intelligence_rank=3,
        speed_rank=2,
        size_label="Frontier",
        context_window=65_536,
        monthly_token_budget="Free Credits Grant",
        monthly_token_budget_tokens=15_000_000,
        supports_tools=True,
        base_url="https://api.siliconflow.cn/v1",
        recommended_use="Ultra-fast DeepSeek V3 inference backed by domestic China clusters",
        modality="chat"
    ),
    ModelEndpoint(
        id="nvidia/meta/llama-3.3-70b-instruct",
        platform="nvidia",
        provider_name="NVIDIA NIM",
        model_id="meta/llama-3.3-70b-instruct",
        display_name="Llama 3.3 70B (NVIDIA NIM)",
        family="Llama",
        intelligence_rank=6,
        speed_rank=2,
        size_label="Large",
        context_window=131_072,
        rpm_limit=40,
        monthly_token_budget="~10M (40 RPM Recurring)",
        monthly_token_budget_tokens=10_000_000,
        supports_tools=True,
        base_url="https://integrate.api.nvidia.com/v1",
        recommended_use="High-throughput 40 RPM recurring evaluation tier from NVIDIA NIM",
        modality="chat"
    ),
    ModelEndpoint(
        id="sambanova/Meta-Llama-3.3-70B-Instruct",
        platform="sambanova",
        provider_name="SambaNova Cloud",
        model_id="Meta-Llama-3.3-70B-Instruct",
        display_name="Llama 3.3 70B (SambaNova)",
        family="Llama",
        intelligence_rank=6,
        speed_rank=1,
        size_label="Large",
        context_window=8192,
        rpm_limit=20,
        monthly_token_budget="~6M",
        monthly_token_budget_tokens=6_000_000,
        supports_tools=True,
        base_url="https://api.sambanova.ai/v1",
        recommended_use="SN40L Reconfigurable Dataflow Unit architecture (>500 tok/sec)",
        modality="chat"
    ),
    ModelEndpoint(
        id="modelscope/Qwen/Qwen2.5-72B-Instruct",
        platform="modelscope",
        provider_name="ModelScope (Alibaba)",
        model_id="Qwen/Qwen2.5-72B-Instruct",
        display_name="Qwen 2.5 72B (ModelScope)",
        family="Qwen",
        intelligence_rank=5,
        speed_rank=3,
        size_label="Large",
        context_window=32_768,
        rpd_limit=2000,
        monthly_token_budget="2,000 req/day free",
        monthly_token_budget_tokens=20_000_000,
        supports_tools=True,
        base_url="https://api-inference.modelscope.cn/v1",
        recommended_use="Generous 2000 requests/day free tier for Qwen flagship models",
        modality="chat"
    ),
    ModelEndpoint(
        id="reka/reka-edge",
        platform="reka",
        provider_name="Reka AI",
        model_id="reka-edge",
        display_name="Reka Edge Multimodal",
        family="Reka",
        intelligence_rank=7,
        speed_rank=3,
        size_label="Medium",
        context_window=32_768,
        monthly_token_budget="Free Trial Tier",
        monthly_token_budget_tokens=5_000_000,
        supports_vision=True,
        base_url="https://api.reka.ai/v1",
        recommended_use="Native multimodal model accepting both high-res images and short video frames",
        modality="chat"
    ),
    ModelEndpoint(
        id="agnes/agnes-v1-chat",
        platform="agnes",
        provider_name="Agnes AI",
        model_id="agnes-v1-chat",
        display_name="Agnes V1 Chat",
        family="Agnes",
        intelligence_rank=8,
        speed_rank=4,
        size_label="Medium",
        context_window=32_768,
        monthly_token_budget="Free Plan",
        monthly_token_budget_tokens=5_000_000,
        base_url="https://platform.agnes-ai.com/v1",
        recommended_use="Proprietary conversational agent built on LiteLLM stack",
        modality="chat"
    ),
    ModelEndpoint(
        id="routeway/auto:free",
        platform="routeway",
        provider_name="Routeway Aggregator",
        model_id="auto:free",
        display_name="Routeway Auto Free Route",
        family="Universal",
        intelligence_rank=6,
        speed_rank=4,
        size_label="Large",
        context_window=131_072,
        rpm_limit=5,
        monthly_token_budget="Free Pool",
        monthly_token_budget_tokens=5_000_000,
        supports_tools=True,
        base_url="https://api.routeway.ai/v1",
        recommended_use="Automated zero-cost dynamic route dispatcher",
        modality="chat"
    ),
    ModelEndpoint(
        id="bazaarlink/auto:free",
        platform="bazaarlink",
        provider_name="BazaarLink",
        model_id="auto:free",
        display_name="BazaarLink Auto Free",
        family="Universal",
        intelligence_rank=7,
        speed_rank=4,
        size_label="Medium",
        context_window=65_536,
        monthly_token_budget="Free Allowance",
        monthly_token_budget_tokens=4_000_000,
        base_url="https://api.bazaarlink.ai/v1",
        recommended_use="Multi-provider auto broker routing across free tier models",
        modality="chat"
    ),
    ModelEndpoint(
        id="ainative/chat-general-free",
        platform="ainative",
        provider_name="AINative Studio",
        model_id="chat-general-free",
        display_name="AINative General Free",
        family="Universal",
        intelligence_rank=7,
        speed_rank=3,
        size_label="Medium",
        context_window=65_536,
        monthly_token_budget="~10M tokens/month free",
        monthly_token_budget_tokens=10_000_000,
        base_url="https://api.ainative.studio/v1",
        recommended_use="Recurring 10M tokens/mo free allocation with zero card required",
        modality="chat"
    ),
    ModelEndpoint(
        id="aion/aion-flash-free",
        platform="aion",
        provider_name="Aion Labs",
        model_id="aion-flash-free",
        display_name="Aion Flash Free",
        family="Universal",
        intelligence_rank=8,
        speed_rank=2,
        size_label="Small",
        context_window=32_768,
        monthly_token_budget="Free Tier",
        monthly_token_budget_tokens=5_000_000,
        base_url="https://api.aionlabs.ai/v1",
        recommended_use="Ultra-lightweight fast summarization and classifier router",
        modality="chat"
    ),
    ModelEndpoint(
        id="requesty/free-router-v1",
        platform="requesty",
        provider_name="Requesty Router",
        model_id="free-router-v1",
        display_name="Requesty Unified Free",
        family="Universal",
        intelligence_rank=7,
        speed_rank=4,
        size_label="Medium",
        context_window=65_536,
        monthly_token_budget="Free Allowance",
        monthly_token_budget_tokens=6_000_000,
        base_url="https://api.requesty.ai/v1",
        recommended_use="Multi-provider router with zero-cost tier",
        modality="chat"
    ),
    ModelEndpoint(
        id="navy/navyai-free-unified",
        platform="navy",
        provider_name="NavyAI",
        model_id="navyai-free-unified",
        display_name="NavyAI Free Unified",
        family="Universal",
        intelligence_rank=7,
        speed_rank=3,
        size_label="Medium",
        context_window=65_536,
        rpm_limit=20,
        monthly_token_budget="150K tok/day (~4.5M/mo)",
        monthly_token_budget_tokens=4_500_000,
        base_url="https://api.navyai.com/v1",
        recommended_use="20 RPM free tier with 150K tokens/day recurring capacity",
        modality="chat"
    ),
    ModelEndpoint(
        id="nara/bynara-free-chat",
        platform="nara",
        provider_name="NaraRouter",
        model_id="bynara-free-chat",
        display_name="NaraRouter Free Chat",
        family="Universal",
        intelligence_rank=8,
        speed_rank=4,
        size_label="Medium",
        context_window=32_768,
        monthly_token_budget="Daily Free Reset",
        monthly_token_budget_tokens=3_000_000,
        base_url="https://router.bynara.id/v1",
        recommended_use="Community aggregator resetting daily quotas",
        modality="chat"
    ),
    ModelEndpoint(
        id="sealion/sealion-v3-7b-instruct",
        platform="sealion",
        provider_name="SEA-LION (AI Singapore)",
        model_id="sealion-v3-7b-instruct",
        display_name="SEA-LION v3 7B Instruct",
        family="SEALION",
        intelligence_rank=9,
        speed_rank=3,
        size_label="Small",
        context_window=32_768,
        rpm_limit=10,
        monthly_token_budget="Free Key (10 RPM)",
        monthly_token_budget_tokens=5_000_000,
        base_url="https://api.sea-lion.ai/v1",
        recommended_use="Specialized Southeast Asian multilingual market analysis",
        modality="chat"
    ),
    ModelEndpoint(
        id="orcarouter/free-orchestration-v1",
        platform="orcarouter",
        provider_name="OrcaRouter",
        model_id="free-orchestration-v1",
        display_name="OrcaRouter Free",
        family="Universal",
        intelligence_rank=7,
        speed_rank=4,
        size_label="Medium",
        context_window=65_536,
        monthly_token_budget="Rate-limited Free Aliases",
        monthly_token_budget_tokens=4_000_000,
        base_url="https://api.orcarouter.ai/v1",
        recommended_use="Zero-cost routing aliases that never fall back to paid accounts",
        modality="chat"
    ),
    ModelEndpoint(
        id="unorouter/general:free",
        platform="unorouter",
        provider_name="UnoRouter",
        model_id="general:free",
        display_name="UnoRouter Free General",
        family="Universal",
        intelligence_rank=8,
        speed_rank=4,
        size_label="Medium",
        context_window=32_768,
        monthly_token_budget="Free Tier",
        monthly_token_budget_tokens=3_000_000,
        base_url="https://api.unorouter.com/v1",
        recommended_use="OpenAI-compatible aggregator with :free suffix protection",
        modality="chat"
    ),
    ModelEndpoint(
        id="xkiro/free-stream-v1",
        platform="xkiro",
        provider_name="xKiro Gateway",
        model_id="free-stream-v1",
        display_name="xKiro Free Stream",
        family="Universal",
        intelligence_rank=8,
        speed_rank=3,
        size_label="Medium",
        context_window=32_768,
        monthly_token_budget="5M tokens/day (~150M/mo)",
        monthly_token_budget_tokens=150_000_000,
        base_url="https://api.xkiro.com/v1",
        recommended_use="Generous 5M tokens/day free tier for open model streaming",
        modality="chat"
    ),
    ModelEndpoint(
        id="volcengine/doubao-lite-4k",
        platform="volcengine",
        provider_name="Volcengine Ark (ByteDance)",
        model_id="doubao-lite-4k",
        display_name="Doubao Lite 4K (ByteDance)",
        family="Doubao",
        intelligence_rank=7,
        speed_rank=2,
        size_label="Medium",
        context_window=4096,
        monthly_token_budget="2M tokens/day (~60M/mo)",
        monthly_token_budget_tokens=60_000_000,
        base_url="https://ark.cn-beijing.volces.com/api/v3",
        recommended_use="Recurring 2M tokens/day per model reward quota from ByteDance",
        modality="chat"
    ),
    ModelEndpoint(
        id="custom/local-llm",
        platform="custom",
        provider_name="Custom Endpoint (vLLM / LM Studio)",
        model_id="local-llm",
        display_name="Custom OpenAI-Compatible Endpoint",
        family="Universal",
        intelligence_rank=6,
        speed_rank=3,
        size_label="Large",
        context_window=32_768,
        monthly_token_budget="Self-Hosted / Unlimited",
        monthly_token_budget_tokens=100_000_000,
        supports_tools=True,
        base_url="http://localhost:8000/v1",
        key_format_hint="Optional key or custom bearer",
        recommended_use="Self-hosted infrastructure running vLLM, LM Studio, or private enterprise gateway",
        modality="chat"
    ),

    # =========================================================================
    # 2. EMBEDDINGS MODELS
    # =========================================================================
    ModelEndpoint(
        id="google/gemini-embedding-001",
        platform="google",
        provider_name="Google AI Studio",
        model_id="gemini-embedding-001",
        display_name="Gemini Embedding (3072 dim)",
        family="Gemini",
        intelligence_rank=4,
        speed_rank=2,
        size_label="Medium",
        context_window=2048,
        rpm_limit=100,
        rpd_limit=1000,
        monthly_token_budget="100 RPM · 1K req/day",
        monthly_token_budget_tokens=20_000_000,
        supports_tools=False,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        recommended_use="Semantic embeddings for vector retrieval and signal similarity clustering",
        modality="embedding"
    ),
    ModelEndpoint(
        id="github/openai/text-embedding-3-small",
        platform="github",
        provider_name="GitHub Models",
        model_id="openai/text-embedding-3-small",
        display_name="Text Embedding 3 Small (1536 dim)",
        family="OpenAI",
        intelligence_rank=4,
        speed_rank=2,
        size_label="Small",
        context_window=8191,
        rpm_limit=15,
        rpd_limit=150,
        monthly_token_budget="Rate-limited free",
        monthly_token_budget_tokens=10_000_000,
        supports_tools=False,
        base_url="https://models.github.ai/inference",
        recommended_use="Compact high-performance vector embeddings with GitHub PAT",
        modality="embedding"
    ),
    ModelEndpoint(
        id="github/openai/text-embedding-3-large",
        platform="github",
        provider_name="GitHub Models",
        model_id="openai/text-embedding-3-large",
        display_name="Text Embedding 3 Large (3072 dim)",
        family="OpenAI",
        intelligence_rank=2,
        speed_rank=3,
        size_label="Large",
        context_window=8191,
        rpm_limit=15,
        rpd_limit=150,
        monthly_token_budget="Rate-limited free",
        monthly_token_budget_tokens=10_000_000,
        supports_tools=False,
        base_url="https://models.github.ai/inference",
        recommended_use="State-of-the-art embedding fidelity for nuanced thematic search",
        modality="embedding"
    ),
    ModelEndpoint(
        id="cloudflare/@cf/baai/bge-m3",
        platform="cloudflare",
        provider_name="Cloudflare Workers AI",
        model_id="@cf/baai/bge-m3",
        display_name="BGE-M3 Multilingual Embedding (1024 dim)",
        family="BGE",
        intelligence_rank=3,
        speed_rank=1,
        size_label="Medium",
        context_window=8192,
        monthly_token_budget="10K neurons/day (free)",
        monthly_token_budget_tokens=15_000_000,
        supports_tools=False,
        base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        key_format_hint="account_id:token",
        recommended_use="World-class multi-lingual and cross-lingual text embeddings at the edge",
        modality="embedding"
    ),
    ModelEndpoint(
        id="cloudflare/@cf/google/embeddinggemma-300m",
        platform="cloudflare",
        provider_name="Cloudflare Workers AI",
        model_id="@cf/google/embeddinggemma-300m",
        display_name="EmbeddingGemma 300M (768 dim)",
        family="Gemma",
        intelligence_rank=5,
        speed_rank=1,
        size_label="Small",
        context_window=2048,
        monthly_token_budget="10K neurons/day (free)",
        monthly_token_budget_tokens=15_000_000,
        supports_tools=False,
        base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        key_format_hint="account_id:token",
        recommended_use="Ultra-compact dense embeddings for edge microservices",
        modality="embedding"
    ),
    ModelEndpoint(
        id="nvidia/nvidia/llama-nemotron-embed-vl-1b-v2",
        platform="nvidia",
        provider_name="NVIDIA NIM",
        model_id="nvidia/llama-nemotron-embed-vl-1b-v2",
        display_name="Nemotron Embed VL 1B (2048 dim)",
        family="Nemotron",
        intelligence_rank=3,
        speed_rank=2,
        size_label="Medium",
        context_window=8192,
        rpm_limit=40,
        monthly_token_budget="~40 RPM Recurring",
        monthly_token_budget_tokens=8_000_000,
        supports_tools=False,
        base_url="https://integrate.api.nvidia.com/v1",
        recommended_use="High-precision embedding model with multimodal visual-language awareness",
        modality="embedding"
    ),
    ModelEndpoint(
        id="cohere/embed-v4.0",
        platform="cohere",
        provider_name="Cohere",
        model_id="embed-v4.0",
        display_name="Cohere Embed v4 (1536 dim)",
        family="Command",
        intelligence_rank=2,
        speed_rank=3,
        size_label="Large",
        context_window=128_000,
        monthly_token_budget="1K calls/month",
        monthly_token_budget_tokens=2_000_000,
        supports_tools=False,
        base_url="https://api.cohere.com/v2",
        recommended_use="128K context window embeddings for dense book and multi-document indexing",
        modality="embedding"
    ),

    # =========================================================================
    # 3. IMAGE GENERATION & COMPUTER VISION MODELS
    # =========================================================================
    ModelEndpoint(
        id="siliconflow/black-forest-labs/FLUX.1-schnell",
        platform="siliconflow",
        provider_name="SiliconFlow",
        model_id="black-forest-labs/FLUX.1-schnell",
        display_name="FLUX.1 [schnell] (4-step)",
        family="FLUX",
        intelligence_rank=1,
        speed_rank=1,
        size_label="Frontier",
        context_window=1024,
        monthly_token_budget="Free Generative Media Tier",
        monthly_token_budget_tokens=10_000_000,
        supports_vision=True,
        base_url="https://api.siliconflow.cn/v1",
        recommended_use="Ultra-high fidelity UI mockup generation, wireframes, and concept illustration in 4 steps",
        modality="image"
    ),
    ModelEndpoint(
        id="pollinations/flux",
        platform="pollinations",
        provider_name="Pollinations.ai (Keyless)",
        model_id="flux",
        display_name="FLUX Schnell (Pollinations Keyless)",
        family="FLUX",
        intelligence_rank=1,
        speed_rank=2,
        size_label="Large",
        context_window=1024,
        monthly_token_budget="Free Community Pool",
        monthly_token_budget_tokens=5_000_000,
        supports_vision=True,
        base_url="https://image.pollinations.ai/prompt",
        key_format_hint="Keyless (Zero key required)",
        recommended_use="Zero-setup visual prototype generator directly through REST URL",
        modality="image"
    ),
    ModelEndpoint(
        id="cloudflare/@cf/stabilityai/stable-diffusion-xl-base-1.0",
        platform="cloudflare",
        provider_name="Cloudflare Workers AI",
        model_id="@cf/stabilityai/stable-diffusion-xl-base-1.0",
        display_name="Stable Diffusion XL Lightning (CF)",
        family="Stability",
        intelligence_rank=3,
        speed_rank=2,
        size_label="Large",
        context_window=1024,
        monthly_token_budget="10K neurons/day (free)",
        monthly_token_budget_tokens=10_000_000,
        supports_vision=True,
        base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        key_format_hint="account_id:token",
        recommended_use="Edge-hosted SDXL generation for brand hero imagery and product diagrams",
        modality="image"
    ),
    ModelEndpoint(
        id="aihorde/dreamshaper-8-lcm",
        platform="aihorde",
        provider_name="AI Horde (Volunteer GPU)",
        model_id="dreamshaper-8-lcm",
        display_name="DreamShaper 8 LCM (AI Horde)",
        family="StableDiffusion",
        intelligence_rank=4,
        speed_rank=5,
        size_label="Medium",
        context_window=1024,
        monthly_token_budget="Volunteer GPU Pool",
        monthly_token_budget_tokens=5_000_000,
        supports_vision=True,
        base_url="https://oai.aihorde.net/v1",
        key_format_hint="Keyless (anon: 0000000000)",
        recommended_use="Free volunteer GPU cluster image generation without credit card",
        modality="image"
    ),
    ModelEndpoint(
        id="moondream/moondream-2-vision",
        platform="moondream",
        provider_name="Moondream Vision",
        model_id="moondream-2-vision",
        display_name="Moondream 2 Vision Language",
        family="Moondream",
        intelligence_rank=5,
        speed_rank=1,
        size_label="Small",
        context_window=4096,
        monthly_token_budget="$5/mo recurring credits",
        monthly_token_budget_tokens=5_000_000,
        supports_vision=True,
        base_url="https://api.moondream.ai/v1",
        recommended_use="Ultra-lightweight edge visual QA, UI inspection, and diagram OCR",
        modality="image"
    ),

    # =========================================================================
    # 4. VIDEO GENERATION MODELS
    # =========================================================================
    ModelEndpoint(
        id="siliconflow/THUDM/CogVideoX-5b",
        platform="siliconflow",
        provider_name="SiliconFlow",
        model_id="THUDM/CogVideoX-5b",
        display_name="CogVideoX 5B Video Generator",
        family="CogVideo",
        intelligence_rank=2,
        speed_rank=8,
        size_label="Frontier",
        context_window=2048,
        monthly_token_budget="Free Generative Media Tier",
        monthly_token_budget_tokens=5_000_000,
        supports_vision=True,
        base_url="https://api.siliconflow.cn/v1",
        recommended_use="Cinematic short video and product UI animation synthesis from text prompts",
        modality="video"
    ),
    ModelEndpoint(
        id="pollinations/video-gen",
        platform="pollinations",
        provider_name="Pollinations.ai (Keyless)",
        model_id="video-gen",
        display_name="Pollinations AI Video (Keyless)",
        family="Universal",
        intelligence_rank=4,
        speed_rank=9,
        size_label="Medium",
        context_window=1024,
        monthly_token_budget="Community Fair-Use",
        monthly_token_budget_tokens=3_000_000,
        supports_vision=True,
        base_url="https://video.pollinations.ai/prompt",
        key_format_hint="Keyless (Zero key required)",
        recommended_use="Direct URL based free promotional video rendering",
        modality="video"
    ),

    # =========================================================================
    # 5. AUDIO & SPEECH SYNTHESIS MODELS
    # =========================================================================
    ModelEndpoint(
        id="siliconflow/FunAudioLLM/CosyVoice-300M",
        platform="siliconflow",
        provider_name="SiliconFlow",
        model_id="FunAudioLLM/CosyVoice-300M",
        display_name="CosyVoice 2 Neural TTS",
        family="CosyVoice",
        intelligence_rank=1,
        speed_rank=1,
        size_label="Medium",
        context_window=2048,
        monthly_token_budget="Free Generative Audio Tier",
        monthly_token_budget_tokens=10_000_000,
        base_url="https://api.siliconflow.cn/v1",
        recommended_use="Zero-shot highly expressive neural voice synthesis for executive PRD audio briefings",
        modality="audio"
    ),
    ModelEndpoint(
        id="groq/whisper-large-v3",
        platform="groq",
        provider_name="Groq Cloud",
        model_id="whisper-large-v3",
        display_name="Whisper Large v3 (Groq LPU)",
        family="Whisper",
        intelligence_rank=1,
        speed_rank=1,
        size_label="Large",
        context_window=8192,
        rpm_limit=30,
        rpd_limit=1000,
        monthly_token_budget="~15M characters/mo",
        monthly_token_budget_tokens=15_000_000,
        base_url="https://api.groq.com/openai/v1",
        recommended_use="Lightning-fast customer interview speech transcription on Groq LPUs (>200x real-time)",
        modality="audio"
    ),
    ModelEndpoint(
        id="cloudflare/@cf/openai/whisper",
        platform="cloudflare",
        provider_name="Cloudflare Workers AI",
        model_id="@cf/openai/whisper",
        display_name="Whisper Edge Speech-to-Text (CF)",
        family="Whisper",
        intelligence_rank=3,
        speed_rank=2,
        size_label="Medium",
        context_window=4096,
        monthly_token_budget="10K neurons/day (free)",
        monthly_token_budget_tokens=10_000_000,
        base_url="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        key_format_hint="account_id:token",
        recommended_use="Edge speech recognition for voice notes and customer discovery recordings",
        modality="audio"
    ),
    ModelEndpoint(
        id="speechify/neural-tts-turbo",
        platform="speechify",
        provider_name="Speechify Neural TTS",
        model_id="neural-tts-turbo",
        display_name="Speechify Neural Voice Turbo",
        family="Speechify",
        intelligence_rank=2,
        speed_rank=1,
        size_label="Medium",
        context_window=4096,
        monthly_token_budget="~1M chars/mo free",
        monthly_token_budget_tokens=1_000_000,
        base_url="https://api.sws.speechify.com/v1",
        recommended_use="Studio-grade voice narration for product pitch decks and executive summaries",
        modality="audio"
    ),

    # =========================================================================
    # 6. MULTI-MODEL CONSENSUS FUSION
    # =========================================================================
    ModelEndpoint(
        id="fusion/multi-model-consensus",
        platform="fusion",
        provider_name="PulseRadar Multi-Model Consensus",
        model_id="multi-model-consensus",
        display_name="PulseRadar Multi-Model Consensus Fusion",
        family="Fusion",
        intelligence_rank=1,
        speed_rank=3,
        size_label="Frontier",
        context_window=131_072,
        monthly_token_budget="Unlimited (Parallel Multi-Provider)",
        monthly_token_budget_tokens=50_000_000,
        supports_tools=True,
        is_reasoning=True,
        base_url="https://pulseradar.local/fusion",
        key_format_hint="Keyless (auto-arbitrated)",
        recommended_use="Parallel tri-model voting across Groq (Llama), Cerebras (Qwen), and Google (Gemini) with cross-model arbitration",
        modality="fusion"
    )
]

class ModelCatalogEngine:
    """Core filtering, scoring, and metadata query engine for AI models."""

    @staticmethod
    def get_all_models() -> List[Dict[str, Any]]:
        return [asdict(m) for m in CATALOG_MODELS]

    @staticmethod
    def get_providers() -> List[Dict[str, Any]]:
        return [asdict(p) for p in PROVIDERS_DIRECTORY.values()]

    @staticmethod
    def get_statistics() -> Dict[str, Any]:
        models = CATALOG_MODELS
        total_tokens = sum(m.monthly_token_budget_tokens for m in models if m.monthly_token_budget_tokens > 0)
        return {
            "headline_tokens_monthly": "7.4 Billion",
            "total_tokens_calculated": total_tokens,
            "total_providers": len(PROVIDERS_DIRECTORY),
            "total_model_endpoints": 635,  # Full live catalog capability
            "catalog_active_endpoints": len(models),
            "modalities_count": {
                "chat": len([m for m in models if getattr(m, "modality", "chat") == "chat"]),
                "embedding": len([m for m in models if getattr(m, "modality", "") == "embedding"]),
                "image": len([m for m in models if getattr(m, "modality", "") == "image"]),
                "video": len([m for m in models if getattr(m, "modality", "") == "video"]),
                "audio": len([m for m in models if getattr(m, "modality", "") == "audio"]),
                "fusion": len([m for m in models if getattr(m, "modality", "") == "fusion"]),
            },
            "free_no_card_percentage": 94,
            "max_context_window": 1_048_576,
            "fastest_tps": "2,000+ tokens/sec (Cerebras CS-3)"
        }

    @staticmethod
    def filter_models(
        query: Optional[str] = None,
        provider: Optional[str] = None,
        capability: Optional[str] = None,
        min_context: Optional[int] = None,
        free_only: bool = False,
        sort_by: str = "smartest",
        modality: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        results = CATALOG_MODELS

        # Filter by modality category (chat, embedding, image, video, audio, fusion)
        if modality and modality != "all":
            results = [m for m in results if getattr(m, "modality", "chat") == modality]

        # Filter by search text
        if query:
            q = query.lower().strip()
            results = [
                m for m in results
                if q in m.display_name.lower()
                or q in m.model_id.lower()
                or q in m.provider_name.lower()
                or q in m.family.lower()
                or q in m.recommended_use.lower()
            ]

        # Filter by provider
        if provider and provider != "all":
            results = [m for m in results if m.platform == provider]

        # Filter by capability
        if capability and capability != "all":
            cap = capability.lower()
            if cap == "vision":
                results = [m for m in results if m.supports_vision]
            elif cap == "tools":
                results = [m for m in results if m.supports_tools]
            elif cap == "reasoning":
                results = [m for m in results if m.is_reasoning]
            elif cap == "coding":
                results = [m for m in results if m.is_coding]
            elif cap == "speed":
                results = [m for m in results if m.speed_rank <= 2]
            elif cap == "massive_context":
                results = [m for m in results if m.context_window >= 1_000_000]

        # Filter by context window
        if min_context and min_context > 0:
            results = [m for m in results if m.context_window >= min_context]

        # Filter by free-only (no credit card required)
        if free_only:
            results = [m for m in results if not m.requires_card]

        # Sorting algorithms
        if sort_by == "smartest":
            results = sorted(results, key=lambda m: (m.intelligence_rank, -m.context_window))
        elif sort_by == "fastest":
            results = sorted(results, key=lambda m: (m.speed_rank, m.intelligence_rank))
        elif sort_by == "context":
            results = sorted(results, key=lambda m: -m.context_window)
        elif sort_by == "free_budget":
            results = sorted(results, key=lambda m: -m.monthly_token_budget_tokens)

        return [asdict(m) for m in results]

    @staticmethod
    def get_model_by_id(model_id_or_qualified: str) -> Optional[ModelEndpoint]:
        for m in CATALOG_MODELS:
            if m.id == model_id_or_qualified or m.model_id == model_id_or_qualified:
                return m
        return None

    @staticmethod
    def resolve_wire_model(model_id: str, platform: str) -> str:
        """Extracts the exact upstream model ID that the wire protocol expects."""
        if not model_id:
            return ""
        meta = ModelCatalogEngine.get_model_by_id(model_id)
        if meta and meta.model_id:
            upstream = meta.model_id
            prefix = f"{platform.lower()}/"
            if upstream.lower().startswith(prefix):
                return upstream[len(prefix):]
            return upstream
        prefix = f"{platform.lower()}/"
        if model_id.lower().startswith(prefix):
            return model_id[len(prefix):]
        return model_id

