"""AI Synthesis Engine & PRD Generator (Anthropic PM Methodology)"""
import logging
from typing import List, Dict, Any, Optional
import httpx
from app.core.config import settings

logger = logging.getLogger(__name__)

class SynthesisEngine:
    async def generate_executive_summary(self, query: str, clusters: List[Dict[str, Any]], total_items: int) -> str:
        """Generates high-level executive summary grounded in discovered clusters."""
        if settings.OPENAI_API_KEY and settings.LLM_PROVIDER == "openai":
            try:
                return await self._call_openai_summary(query, clusters, total_items)
            except Exception as e:
                logger.error(f"OpenAI summary failed: {e}. Falling back to structured synthesizer.")

        # Built-in structured synthesis
        top_cluster = clusters[0] if clusters else None
        pain_count = sum(1 for c in clusters if c["category"] == "PAIN_POINT")
        desire_count = sum(1 for c in clusters if c["category"] == "DESIRE")

        summary = (
            f"### Strategic Research Summary: {query}\n\n"
            f"Based on **{total_items} verified feedback items** analyzed across social discussions and video transcripts, "
            f"user sentiment reveals **{len(clusters)} core thematic clusters** ({pain_count} high-friction pain points, {desire_count} unfulfilled feature requests).\n\n"
            f"**Key Findings:**\n"
            f"- **Primary Friction:** {top_cluster['title'] if top_cluster else 'Performance & setup complexity'}.\n"
            f"- **User Mental Model:** Users expect zero-config scalability and clear migration pathways, but experience friction when moving from hobby prototypes to production workloads.\n"
            f"- **Strategic Recommendation:** Prioritize developer ergonomics, predictable pricing boundaries, and native error diagnostics before introducing secondary surface features."
        )
        return summary

    async def generate_prd(self, query: str, clusters: List[Dict[str, Any]], custom_instructions: Optional[str] = None) -> str:
        """Generates a complete, professional PRD based on discovered evidence."""
        if settings.OPENAI_API_KEY and settings.LLM_PROVIDER == "openai":
            try:
                return await self._call_openai_prd(query, clusters, custom_instructions)
            except Exception as e:
                logger.error(f"OpenAI PRD generation failed: {e}. Using structured PRD generator.")

        # Grounded rule-based PRD template incorporating real clusters and quotes
        prd_lines = [
            f"# Product Requirements Document (PRD): Next-Gen Solution for {query}",
            "",
            "> **Generated by PulseRadar** | *Grounded in multi-channel customer feedback*",
            "",
            "## 1. Executive Summary & Problem Statement",
            f"Customer discovery indicates significant developer dissatisfaction in the **{query}** ecosystem.",
            f"Across {len(clusters)} major feedback clusters, users report friction that impacts developer velocity and leads to churn.",
            ""
        ]

        if custom_instructions:
            prd_lines.extend([
                f"> **Custom Strategic Focus:** {custom_instructions}",
                ""
            ])

        prd_lines.extend([
            "## 2. Evidence-Backed User Pain Points",
            ""
        ])

        for i, c in enumerate(clusters[:3], 1):
            prd_lines.append(f"### {i}. {c['title']} ({c['category'].replace('_', ' ').title()})")
            prd_lines.append(f"*{c['description']}*")
            if c.get("quotes"):
                top_q = c["quotes"][0]
                prd_lines.append(f"> \"{top_q['quote_text']}\"")
                prd_lines.append(f"> — *Source: [{top_q.get('source_author', 'Verified User')}]({top_q['permalink']})*")
            prd_lines.append("")

        prd_lines.extend([
            "## 3. Target User Persona",
            f"- **Role:** Senior Full-Stack Engineer / Technical Founder evaluating {query}.",
            "- **Core Goal:** Fast time-to-market without incurring unexpected operational overhead or vendor lock-in.",
            "- **Mental Model:** 'It should just work out of the box with modern tooling and edge environments.'",
            "",
            "## 4. Functional Requirements",
            "- **FR-1 (Automatic Circuit Breaking & Telemetry):** System shall detect failing downstream connections and alert the developer with actionable diagnostics.",
            "- **FR-2 (Transparent Cost & Resource Profiling):** Provide real-time estimates of operational costs and concurrency limits.",
            "- **FR-3 (Drop-in Compatibility Layer):** Seamless migration tooling with zero code rewrite required.",
            "",
            "## 5. User Stories & Acceptance Criteria",
            "```gherkin",
            "Feature: Frictionless Deployment & Error Diagnostic",
            "",
            "  Scenario: Developer experiences high concurrency spikes",
            "    Given a sustained spike of 2,000 requests per minute",
            "    When resource thresholds exceed 85%",
            "    Then the system automatically queues requests with a Retry-After header",
            "    And dispatches a real-time warning to the configured webhook",
            "```",
            "",
            "## 6. Success Metrics (OKRs)",
            "- **Reduction in Churn:** Decrease migration away from the product by 35% within 90 days.",
            "- **Time to Resolution:** Reduce debugging time for connection failures from 4 hours to < 5 minutes.",
            "- **Community Net Promoter Score (NPS):** Increase developer sentiment score from Neutral (-0.1) to Positive (+0.6)."
        ])

        return "\n".join(prd_lines)

    async def _call_openai_summary(self, query: str, clusters: List[Dict[str, Any]], total_items: int) -> str:
        prompt = (
            f"You are an expert Chief Product Officer. Synthesize an executive product discovery summary for: '{query}'.\n"
            f"Total items analyzed: {total_items}.\n"
            f"Clusters: {clusters}\n"
            "Format in clean markdown with Strategic Takeaways, User Mental Models, and Action Items."
        )
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {settings.OPENAI_API_KEY}"},
                json={
                    "model": settings.OPENAI_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.4
                }
            )
            data = resp.json()
            return data["choices"][0]["message"]["content"]

    async def _call_openai_prd(self, query: str, clusters: List[Dict[str, Any]], custom_instructions: Optional[str]) -> str:
        prompt = (
            f"You are a Principal Product Manager. Generate a comprehensive Product Requirements Document (PRD) for a project solving issues with: '{query}'.\n"
            f"Based on real user evidence clusters: {clusters}\n"
            f"Custom focus: {custom_instructions or 'None'}\n"
            "Include: Problem Statement, Personas, Functional Requirements (FR-1, FR-2), Gherkin User Stories (Given-When-Then), and OKRs."
        )
        async with httpx.AsyncClient(timeout=45) as client:
            resp = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {settings.OPENAI_API_KEY}"},
                json={
                    "model": settings.OPENAI_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.3
                }
            )
            data = resp.json()
            return data["choices"][0]["message"]["content"]
